const { defineConfig } = require('@vue/cli-service')
const fs = require('fs')
const path = require('path')

// Check if SSL certificates exist and are accessible
const sslKeyPath = path.join(__dirname, 'ssl', 'key.pem')
const sslCertPath = path.join(__dirname, 'ssl', 'cert.pem')
let hasSSL = false

try {
  if (fs.existsSync(sslKeyPath) && fs.existsSync(sslCertPath)) {
    // Test if we can actually read the files
    fs.readFileSync(sslKeyPath)
    fs.readFileSync(sslCertPath)
    hasSSL = true
  }
} catch (error) {
  console.log('SSL certificates exist but are not readable, falling back to auto-generated certificates')
  hasSSL = false
}

module.exports = defineConfig({
  transpileDependencies: true,
  
  configureWebpack: {
    resolve: {
      fallback: {
        "http": require.resolve("stream-http"),
        "https": require.resolve("https-browserify"),
        "util": require.resolve("util/"),
        "zlib": require.resolve("browserify-zlib"),
        "stream": require.resolve("stream-browserify"),
        "url": require.resolve("url/"),
        "crypto": require.resolve("crypto-browserify"),
        "assert": require.resolve("assert/")
      }
    }
  },

  chainWebpack: config => {
    config.resolve.fallback = {
      "http": require.resolve("stream-http"),
      "https": require.resolve("https-browserify"), 
      "util": require.resolve("util/"),
      "zlib": require.resolve("browserify-zlib"),
      "stream": require.resolve("stream-browserify"),
      "url": require.resolve("url/"),
      "crypto": require.resolve("crypto-browserify"),
      "assert": require.resolve("assert/")
    }
  },
  
  devServer: {
    host: '0.0.0.0',
    port: 8080,
    allowedHosts: 'all',
    client: {
      webSocketURL: 'auto://0.0.0.0:0/ws',
      overlay: {
        runtimeErrors: (error) => {
          // Suppress harmless ResizeObserver errors
          if (error.message && error.message.includes('ResizeObserver loop')) {
            return false;
          }
          return true;
        }
      }
    },
    // Always enable HTTPS - certificates will be generated by startup script
    https: hasSSL ? {
      key: fs.readFileSync(sslKeyPath),
      cert: fs.readFileSync(sslCertPath)
    } : true,
    proxy: {
      '/api': {
        target: 'http://server:80',
        changeOrigin: true,
        secure: false,
        timeout: 300000  // 5 minutes for long-running LLM operations
      },
      '/assetid': {
        target: 'http://server:80',
        changeOrigin: true,
        secure: false
      },
      '/newAssetID': {
        target: 'http://server:80',
        changeOrigin: true,
        secure: false
      },
      '/health': {
        target: 'http://server:80',
        changeOrigin: true,
        secure: false
      },
      '/episodes': {
        target: 'http://server:80',
        changeOrigin: true,
        secure: false
      },
      '/scripts': {
        target: 'http://server:80',
        changeOrigin: true,
        secure: false
      },
      '/asterisk-ws': {
        target: 'ws://192.168.51.223:8088/ws',
        changeOrigin: true,
        ws: true,
        secure: false,
        pathRewrite: {
          '^/asterisk-ws': ''
        }
      }
    }
  }
});
