const { defineConfig } = require('@vue/cli-service')
const fs = require('fs')
const path = require('path')

// Override follow-redirects default 10MB body limit for large video uploads
const followRedirects = require('follow-redirects')
followRedirects.maxBodyLength = 10 * 1024 * 1024 * 1024 // 10GB

// Backend proxy target. Defaults to the docker-network hostname used by the
// production container (`server:80`). When running the dev server on the HOST
// (e.g. the migration worktree harness), `server` does not resolve — set
// DEV_API_TARGET=http://localhost:8888 to proxy to the host-published backend.
const API_TARGET = process.env.DEV_API_TARGET || 'http://server:80'

// Check if SSL certificates exist and are accessible
const sslKeyPath = path.join(__dirname, 'ssl', 'key.pem')
const sslCertPath = path.join(__dirname, 'ssl', 'cert.pem')
let hasSSL = false

try {
  if (fs.existsSync(sslKeyPath) && fs.existsSync(sslCertPath)) {
    // Test if we can actually read the files
    fs.readFileSync(sslKeyPath)
    fs.readFileSync(sslCertPath)
    hasSSL = true
  }
} catch (error) {
  console.log('SSL certificates exist but are not readable, falling back to auto-generated certificates')
  hasSSL = false
}

module.exports = defineConfig({
  transpileDependencies: true,
  
  configureWebpack: {
    resolve: {
      fallback: {
        "http": require.resolve("stream-http"),
        "https": require.resolve("https-browserify"),
        "util": require.resolve("util/"),
        "zlib": require.resolve("browserify-zlib"),
        "stream": require.resolve("stream-browserify"),
        "url": require.resolve("url/"),
        "crypto": require.resolve("crypto-browserify"),
        "assert": require.resolve("assert/")
      }
    }
  },

  chainWebpack: config => {
    config.resolve.fallback = {
      "http": require.resolve("stream-http"),
      "https": require.resolve("https-browserify"), 
      "util": require.resolve("util/"),
      "zlib": require.resolve("browserify-zlib"),
      "stream": require.resolve("stream-browserify"),
      "url": require.resolve("url/"),
      "crypto": require.resolve("crypto-browserify"),
      "assert": require.resolve("assert/")
    }
  },
  
  devServer: {
    host: '0.0.0.0',
    port: 8080,
    allowedHosts: 'all',
    // SPA history fallback: serve index.html for deep routes so a HARD reload /
    // bookmark / shared link to e.g. /content-editor/0278 loads the app instead
    // of 404ing. Without this, F5 on any route other than "/" returns a 404 page
    // (no editor, no needs-attention highlights) because webpack-dev-server has
    // no fallback configured by default once devServer is customized.
    historyApiFallback: true,
    // Behind the Cloudflare tunnel, Cloudflare was CACHING the bundle
    // (cache-control: max-age=14400) and serving a STALE app.js — including an
    // old HMR client — to browsers regardless of hard-refresh/incognito (edge
    // cache, not browser cache). Send no-store so Cloudflare never caches the
    // dev server's responses. Applies to BOTH the dev tunnel (DEV_API_TARGET)
    // and the LIVE tunnel/showbuild.app (DISABLE_HMR) — both are served through
    // Cloudflare and must not have their bundle edge-cached.
    ...((process.env.DEV_API_TARGET || process.env.DISABLE_HMR)
      ? {
          headers: {
            'Cache-Control': 'no-store, no-cache, must-revalidate, max-age=0',
            Pragma: 'no-cache',
            Expires: '0',
          },
        }
      : {}),
    // When this dev server is served through the Cloudflare tunnel (the dev
    // site via DEV_API_TARGET, OR the LIVE site at showbuild.app — which also
    // runs this vue-cli dev server behind the tunnel), the HMR websocket can't
    // reach back through the tunnel. Its failed reconnects trigger an endless
    // full-page reload loop ("flashing"). Disable HMR + live-reload whenever
    // EITHER flag is set; a manual refresh after a rebuild is fine. Only a plain
    // LAN/in-docker dev server (neither flag) keeps normal hot-reload.
    hot: (process.env.DEV_API_TARGET || process.env.DISABLE_HMR) ? false : true,
    liveReload: (process.env.DEV_API_TARGET || process.env.DISABLE_HMR) ? false : true,
    client: (process.env.DEV_API_TARGET || process.env.DISABLE_HMR)
      ? false
      : {
          webSocketURL: 'auto://0.0.0.0:0/ws',
          overlay: {
            runtimeErrors: (error) => {
              // Suppress harmless ResizeObserver errors
              if (error.message && error.message.includes('ResizeObserver loop')) {
                return false;
              }
              return true;
            }
          }
        },
    // Always enable HTTPS - certificates will be generated by startup script
    https: hasSSL ? {
      key: fs.readFileSync(sslKeyPath),
      cert: fs.readFileSync(sslCertPath)
    } : true,
    proxy: {
      '/api': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false,
        // The backend issues a 307 to normalize trailing slashes, and because
        // the frontend is HTTPS it builds the Location from X-Forwarded-Proto
        // as `https://server:80/...` — an internal docker host on the wrong
        // scheme/port that neither the proxy nor the browser can follow
        // (was EPROTO with followRedirects on; an unfollowable 307 with it off).
        // Rewrite the redirect Location back to the browser-facing origin so
        // the client follows it cleanly. Keep followRedirects OFF.
        autoRewrite: true,
        protocolRewrite: 'https',
        timeout: 300000  // 5 minutes for long-running LLM operations
      },
      '/assetid': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      '/newAssetID': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      '/health': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      '/episodes': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      '/scripts': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      '/media_assets': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      // Unbound media pool (cue-released + whiteboard media moved here from /repo).
      '/pool': {
        target: API_TARGET,
        changeOrigin: true,
        secure: false
      },
      '/asterisk-ws': {
        target: 'ws://192.168.51.223:8088/ws',
        changeOrigin: true,
        ws: true,
        secure: false,
        pathRewrite: {
          '^/asterisk-ws': ''
        }
      }
    }
  }
});
