<template>
  <v-dialog
    :model-value="modelValue"
    @update:model-value="$emit('update:modelValue', $event)"
    width="75vw"
    max-width="1100px"
    scrollable
    persistent
  >
    <v-card class="episode-details-modal d-flex flex-column" height="80vh">
      <v-card-title class="modal-header d-flex align-center pa-2 pl-4">
        <v-icon class="me-2" size="small">mdi-square-edit-outline</v-icon>
        <span class="text-subtitle-1 font-weight-medium">Edit Episode Details</span>
        <v-chip v-if="episodeNumber" size="x-small" variant="tonal" color="primary" class="ms-3">
          EP {{ episodeNumber }}
        </v-chip>
        <v-spacer />
        <v-btn icon="mdi-close" variant="text" size="small" @click="$emit('update:modelValue', false)" />
      </v-card-title>

      <v-tabs v-model="activeTab" color="primary" density="compact" show-arrows class="modal-tabs">
        <v-tab value="basic">
          <v-icon start size="x-small">mdi-information-outline</v-icon>
          Basic Info
        </v-tab>
        <v-tab value="people">
          <v-icon start size="x-small">mdi-account-multiple</v-icon>
          People
        </v-tab>
        <v-tab value="distribution">
          <v-icon start size="x-small">mdi-share-variant</v-icon>
          Distribution
        </v-tab>
      </v-tabs>

      <v-divider />

      <v-card-text class="flex-grow-1 pa-0 modal-body" style="overflow-y: auto;">
        <v-window v-model="activeTab" class="fill-height">
          <!-- Basic Info -->
          <v-window-item value="basic">
            <div class="basic-tab pa-6">

              <!-- Top row: Title/Subtitle/Slug (left)  +  Identity (right) -->
              <v-row dense class="top-row">
                <v-col cols="12" md="9">
                  <section class="section h-100">
                    <header class="section-head">
                      <v-icon size="x-small" class="me-2" color="grey-darken-1">mdi-text-box-outline</v-icon>
                      <span>Overview</span>
                      <span v-if="descriptionModel" class="section-hint">Description generated by {{ descriptionModel }}</span>
                    </header>
                    <div class="stacked-fields mt-1">
                      <v-text-field
                        label="Title"
                        :model-value="episodeTitle"
                        @update:model-value="$emit('update:episodeTitle', $event)"
                        variant="outlined"
                        density="compact"
                        hide-details
                        persistent-placeholder
                        placeholder="Untitled Episode"
                        class="compact-field"
                      />
                      <v-text-field
                        label="Subtitle"
                        :model-value="subtitle"
                        @update:model-value="$emit('update:subtitle', $event)"
                        variant="outlined"
                        density="compact"
                        hide-details
                        persistent-placeholder
                        placeholder="Short tagline"
                        class="compact-field"
                      />
                      <v-textarea
                        label="Description"
                        :model-value="description"
                        @update:model-value="$emit('update:description', $event)"
                        variant="outlined"
                        density="compact"
                        hide-details
                        persistent-placeholder
                        auto-grow
                        rows="4"
                        placeholder="Type a description of this episode"
                        class="compact-field description-field"
                      />
                    </div>
                  </section>
                </v-col>
                <v-col cols="12" md="3">
                  <section class="section h-100">
                    <header class="section-head">
                      <v-icon size="x-small" class="me-2" color="grey-darken-1">mdi-calendar-clock</v-icon>
                      <span>Schedule &amp; Status</span>
                    </header>
                    <div class="stacked-fields mt-1">
                      <div class="status-picker">
                        <div class="status-picker-label">Status</div>
                        <v-menu offset="4" :close-on-content-click="true">
                          <template #activator="{ props: menuProps }">
                            <v-chip
                              v-bind="menuProps"
                              :color="getStatusColor(productionStatus)"
                              variant="flat"
                              size="small"
                              rounded="0"
                              class="status-pill"
                            >
                              {{ (productionStatus || 'unknown').toUpperCase() }}
                            </v-chip>
                          </template>
                          <v-card class="status-menu-card pa-2" min-width="180">
                            <v-btn
                              v-for="opt in productionStatuses"
                              :key="opt.value"
                              :color="getStatusColor(opt.value)"
                              variant="flat"
                              size="small"
                              block
                              rounded="0"
                              class="mb-1 status-menu-btn"
                              :disabled="productionStatus === opt.value"
                              @click="$emit('update:productionStatus', opt.value)"
                            >
                              {{ opt.title.toUpperCase() }}
                            </v-btn>
                          </v-card>
                        </v-menu>
                      </div>
                      <v-text-field
                        label="Air Date"
                        :model-value="airDateInput"
                        @update:model-value="$emit('update:airDate', $event)"
                        type="date"
                        variant="outlined"
                        density="compact"
                        hide-details
                        persistent-placeholder
                        class="compact-field"
                      />
                      <v-text-field
                        label="Air Time"
                        :model-value="airTimeInput"
                        @update:model-value="$emit('update:airTime', $event)"
                        type="time"
                        variant="outlined"
                        density="compact"
                        hide-details
                        persistent-placeholder
                        class="compact-field"
                      />
                      <v-select
                        label="Timezone"
                        :model-value="airTimezone"
                        @update:model-value="$emit('update:airTimezone', $event)"
                        :items="timezoneOptions"
                        variant="outlined"
                        density="compact"
                        hide-details
                        persistent-placeholder
                        class="compact-field"
                      />
                    </div>
                  </section>
                </v-col>
              </v-row>

              <!-- Identity (read-only identifiers) -->
              <section class="section">
                <header class="section-head">
                  <v-icon size="x-small" class="me-2" color="grey-darken-1">mdi-card-account-details-outline</v-icon>
                  <span>Identity</span>
                </header>
                <v-row dense class="mt-1">
                  <v-col cols="12" md="4">
                    <v-text-field
                      label="Total Duration"
                      :model-value="duration"
                      readonly
                      disabled
                      variant="outlined"
                      density="compact"
                      hide-details
                      persistent-placeholder
                      class="compact-field readonly-field"
                    />
                  </v-col>
                  <v-col cols="12" md="3">
                    <v-text-field
                      label="Episode #"
                      :model-value="episodeNumber"
                      readonly
                      disabled
                      variant="outlined"
                      density="compact"
                      hide-details
                      persistent-placeholder
                      class="compact-field readonly-field"
                    />
                  </v-col>
                  <v-col cols="12" md="5">
                    <v-text-field
                      label="Episode Asset ID"
                      :model-value="episodeAssetId"
                      readonly
                      disabled
                      variant="outlined"
                      density="compact"
                      hide-details
                      persistent-placeholder
                      class="compact-field readonly-field"
                    />
                  </v-col>
                </v-row>
              </section>

            </div>
          </v-window-item>

          <v-window-item value="people">
            <div class="basic-tab pa-6">
              <section class="section">
                <header class="section-head">
                  <v-icon size="x-small" class="me-2" color="grey-darken-1">mdi-account-multiple</v-icon>
                  <span>People</span>
                </header>
                <v-row dense class="mt-1">
                  <v-col cols="12">
                    <v-text-field
                      label="Guest"
                      :model-value="guest"
                      @update:model-value="$emit('update:guest', $event)"
                      variant="outlined"
                      density="compact"
                      hide-details
                      persistent-placeholder
                      placeholder="Guest name(s)"
                      class="compact-field"
                    />
                  </v-col>
                </v-row>
              </section>
            </div>
          </v-window-item>

          <v-window-item value="distribution">
            <div class="placeholder-tab">
              <v-icon size="56" color="grey-lighten-1">mdi-share-variant-outline</v-icon>
              <p class="placeholder-title">Distribution</p>
              <p class="placeholder-sub">Publishing targets, release windows, and platform-specific settings.</p>
            </div>
          </v-window-item>

        </v-window>
      </v-card-text>

      <v-divider />

      <v-card-actions class="pa-2 pe-3">
        <v-spacer />
        <v-btn variant="text" size="small" @click="$emit('update:modelValue', false)">Close</v-btn>
        <v-btn color="primary" variant="elevated" size="small" prepend-icon="mdi-content-save" @click="onSave">
          Save
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { getColorValue, resolveVuetifyColor } from '@/utils/themeColorMap'
import { registerModalEsc } from '@/composables/useModalStack'

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  episodeNumber: { type: String, default: '' },
  episodeAssetId: { type: String, default: '' },
  episodeTitle: { type: String, default: '' },
  subtitle: { type: String, default: '' },
  slug: { type: String, default: '' },
  guest: { type: String, default: '' },
  description: { type: String, default: '' },
  descriptionModel: { type: String, default: '' },
  airDate: { type: String, default: '' },
  airTime: { type: String, default: '' },
  airTimezone: { type: String, default: 'America/New_York' },
  productionStatus: { type: String, default: 'draft' },
  productionStatuses: {
    type: Array,
    default: () => [
      { title: 'Scheduled', value: 'scheduled' },
      { title: 'Draft', value: 'draft' },
      { title: 'Production', value: 'production' },
      { title: 'Running', value: 'running' },
      { title: 'Completed', value: 'completed' }
    ]
  },
  duration: { type: String, default: '00:00:00' }
})

const emit = defineEmits([
  'update:modelValue',
  'update:episodeTitle',
  'update:subtitle',
  'update:slug',
  'update:guest',
  'update:description',
  'update:airDate',
  'update:airTime',
  'update:airTimezone',
  'update:productionStatus',
  'save'
])

const activeTab = ref('basic')

watch(() => props.modelValue, (open) => {
  if (open) activeTab.value = 'basic'
})

// Site-wide ESC-closes-modal behavior.
registerModalEsc(() => props.modelValue, () => emit('update:modelValue', false), 'EpisodeDetailsModal')

const timezoneOptions = [
  { title: 'ET', value: 'America/New_York' },
  { title: 'CT', value: 'America/Chicago' },
  { title: 'MT', value: 'America/Denver' },
  { title: 'PT', value: 'America/Los_Angeles' },
  { title: 'UTC', value: 'UTC' }
]

// Normalize incoming airDate/airTime so the native HTML date/time inputs
// can render them. The parent may pass a full ISO datetime, a date-only
// string, or empty.
const airDateInput = computed(() => {
  const v = props.airDate
  if (!v) return ''
  // Already YYYY-MM-DD
  if (/^\d{4}-\d{2}-\d{2}$/.test(v)) return v
  // ISO datetime — strip after the 'T' or ' '
  const m = String(v).match(/^(\d{4}-\d{2}-\d{2})/)
  return m ? m[1] : ''
})

const airTimeInput = computed(() => {
  const v = props.airTime
  if (!v) return ''
  // Strip seconds if present (HH:MM:SS -> HH:MM)
  const m = String(v).match(/^(\d{2}:\d{2})/)
  return m ? m[1] : ''
})

function getStatusColor(status) {
  if (!status) return 'grey'
  try {
    const colorName = getColorValue(String(status).toLowerCase())
    const resolved = resolveVuetifyColor(colorName)
    return resolved || colorName || 'grey'
  } catch {
    return 'grey'
  }
}


function onSave() {
  emit('save')
  emit('update:modelValue', false)
}
</script>

<style scoped>
.episode-details-modal {
  background: #fafafa;
  font-size: 0.85rem;
}

.modal-header {
  background: #fff;
  border-bottom: 1px solid rgba(0, 0, 0, 0.08);
  min-height: 0;
}

.modal-tabs {
  background: #fff;
  min-height: 36px;
}

:deep(.modal-tabs .v-tab) {
  font-size: 0.75rem !important;
  text-transform: none !important;
  letter-spacing: 0 !important;
  min-height: 36px !important;
  height: 36px !important;
  padding: 0 12px !important;
}

.modal-body {
  background: #fafafa;
}

.basic-tab {
  max-width: 1200px;
  margin: 0 auto;
}

.section {
  background: #fff;
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 6px;
  padding: 14px 16px 12px;
  margin-bottom: 14px;
}

.section.h-100 {
  height: 100%;
  margin-bottom: 0;
}

.top-row {
  margin-bottom: 14px;
}

.stacked-fields {
  display: flex;
  flex-direction: column;
  gap: 22px;
  padding-top: 6px;
}

.stacked-fields > .compact-field {
  margin-bottom: 0 !important;
}

/* Add breathing room between any stacked compact-fields inside a v-row */
:deep(.v-row.mt-1 > .v-col) {
  padding-top: 12px !important;
  padding-bottom: 12px !important;
}

.section-head {
  display: flex;
  align-items: center;
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.6px;
  color: #555;
  padding-bottom: 8px;
  margin-bottom: 14px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
}

.section-hint {
  margin-left: auto;
  font-size: 0.65rem;
  font-weight: 500;
  text-transform: none;
  letter-spacing: 0;
  color: #7e57c2;
  font-style: italic;
}

/* Compact field styling — smaller fonts, slim height.
   Note: do NOT override v-field__input padding — Vuetify uses it to anchor
   the floating label correctly on the top border. */
:deep(.compact-field .v-field__input) {
  font-size: 0.82rem !important;
  min-height: 36px !important;
}

:deep(.compact-field .v-field-label) {
  font-size: 0.78rem !important;
}

/* Pull the floating label down so it sits ON the top border line
   (creating the notch), not floating above it. */
:deep(.compact-field .v-field-label--floating) {
  top: 0 !important;
  transform: translateY(-50%) !important;
  font-size: 0.7rem !important;
  background: #fff;
  padding: 0 4px;
  line-height: 1;
}

:deep(.compact-field .v-field--variant-outlined .v-field__outline__start),
:deep(.compact-field .v-field--variant-outlined .v-field__outline__end) {
  --v-field-padding-start: 8px;
}

:deep(.compact-field input),
:deep(.compact-field textarea) {
  font-size: 0.85rem !important;
}

/* Description: pure auto-grow, no internal scrollbar, no max-height clamp */
:deep(.description-field .v-field__input) {
  padding-top: 6px !important;
  padding-bottom: 6px !important;
  max-height: none !important;
  overflow: visible !important;
}

:deep(.description-field textarea) {
  line-height: 1.5 !important;
  font-size: 0.88rem !important;
  max-height: none !important;
  overflow: hidden !important;  /* auto-grow sizes the box; no inner scroll */
  resize: none !important;
}

.description-section {
  height: 100%;
  margin-bottom: 0;
  display: flex;
  flex-direction: column;
}

.description-section .v-textarea {
  flex: 1;
}

.body-row {
  margin-bottom: 0;
}

.body-left-col > .section:last-child {
  margin-bottom: 0;
}

.body-right-col {
  display: flex;
}

.body-right-col > .section {
  width: 100%;
}

/* Read-only fields: visually de-emphasized but still legible */
:deep(.readonly-field .v-field) {
  background: rgba(0, 0, 0, 0.025) !important;
}

:deep(.readonly-field input) {
  color: rgba(0, 0, 0, 0.65) !important;
  -webkit-text-fill-color: rgba(0, 0, 0, 0.65) !important;
}

:deep(.readonly-field .v-field--disabled) {
  opacity: 1 !important;
}

/* Production status: tint border with the resolved status color */
.status-field {
  --status-tint: transparent;
}

:deep(.status-field .v-field--variant-outlined .v-field__outline) {
  --v-field-border-opacity: 1;
  --v-field-border-width: 1.5px;
}

:deep(.status-field .v-field--variant-outlined .v-field__outline__start),
:deep(.status-field .v-field--variant-outlined .v-field__outline__notch::before),
:deep(.status-field .v-field--variant-outlined .v-field__outline__notch::after),
:deep(.status-field .v-field--variant-outlined .v-field__outline__end) {
  border-color: var(--status-tint) !important;
}

.status-chip-inline {
  text-transform: uppercase;
  letter-spacing: 0.5px;
  font-weight: 700;
  font-size: 0.65rem !important;
}

/* Production Status — clickable colored bar (matches EpisodesView pattern) */
.status-picker {
  display: flex;
  flex-direction: column;
}

.status-picker-label {
  font-size: 0.7rem;
  font-weight: 500;
  color: rgba(0, 0, 0, 0.6);
  margin-bottom: 6px;
  padding-left: 2px;
}

:deep(.status-pill) {
  width: 100% !important;
  min-height: 36px !important;
  height: 36px !important;
  font-weight: 600 !important;
  font-size: 0.78rem !important;
  letter-spacing: 0.8px !important;
  cursor: pointer;
  transition: opacity 0.2s ease, transform 0.1s ease;
}

:deep(.status-pill:hover) {
  opacity: 0.9;
}

:deep(.status-pill .v-chip__content) {
  width: 100%;
  justify-content: center;
}

.status-menu-card {
  border-radius: 4px;
}

:deep(.status-menu-btn) {
  font-weight: 600 !important;
  letter-spacing: 0.6px !important;
  font-size: 0.75rem !important;
}

/* Placeholder tabs */
.placeholder-tab {
  text-align: center;
  padding: 80px 20px;
  color: rgba(0, 0, 0, 0.45);
}

.placeholder-title {
  margin-top: 12px;
  font-size: 1.1rem;
  font-weight: 600;
  color: rgba(0, 0, 0, 0.65);
}

.placeholder-sub {
  margin-top: 4px;
  font-size: 0.8rem;
}
</style>
