"""add_rbac_system

Revision ID: 0e73074190a2
Revises: 008_rename_to_episode_templates
Create Date: 2025-08-13 12:46:27.510611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e73074190a2'
down_revision = '008_rename_to_episode_templates'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('auto_assign_new_users', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_index(op.f('ix_groups_organization_id'), 'groups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=False)
    op.create_table('rbac_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbac_audit_log_action'), 'rbac_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_rbac_audit_log_created_at'), 'rbac_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_rbac_audit_log_id'), 'rbac_audit_log', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_role_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('group_roles',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('added_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permission_overrides_id'), 'user_permission_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_permission_id'), 'user_permission_overrides', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_index(op.f('ix_asset_id_relationships_id'), table_name='asset_id_relationships')
    op.drop_index(op.f('ix_asset_id_relationships_relationship_type'), table_name='asset_id_relationships')
    op.drop_index(op.f('ix_asset_id_relationships_source_asset_id'), table_name='asset_id_relationships')
    op.drop_index(op.f('ix_asset_id_relationships_target_asset_id'), table_name='asset_id_relationships')
    op.drop_table('asset_id_relationships')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_slug'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_id_pending_messages_id'), table_name='asset_id_pending_messages')
    op.drop_index(op.f('ix_asset_id_pending_messages_pending_asset_id'), table_name='asset_id_pending_messages')
    op.drop_table('asset_id_pending_messages')
    op.drop_index(op.f('ix_scaffold_episodes_episode_number'), table_name='episode_templates')
    op.drop_index(op.f('ix_scaffold_episodes_organization_id'), table_name='episode_templates')
    op.drop_index(op.f('ix_scaffold_episodes_status'), table_name='episode_templates')
    op.drop_table('episode_templates')
    op.drop_index(op.f('ix_blueprint_nodes_parent_id'), table_name='blueprint_nodes')
    op.drop_index(op.f('ix_blueprint_nodes_template_id'), table_name='blueprint_nodes')
    op.drop_table('blueprint_nodes')
    op.drop_index(op.f('ix_blueprint_templates_name'), table_name='blueprint_templates')
    op.drop_index(op.f('ix_blueprint_templates_template_type'), table_name='blueprint_templates')
    op.drop_table('blueprint_templates')
    op.drop_index(op.f('ix_extracted_quotes_id'), table_name='extracted_quotes')
    op.drop_index(op.f('ix_extracted_quotes_quote_id'), table_name='extracted_quotes')
    op.drop_index(op.f('ix_extracted_quotes_slug'), table_name='extracted_quotes')
    op.drop_table('extracted_quotes')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_rundown_items_legacy_asset_id'), table_name='rundown_items_legacy')
    op.drop_index(op.f('ix_rundown_items_legacy_id'), table_name='rundown_items_legacy')
    op.drop_index(op.f('ix_rundown_items_legacy_slug'), table_name='rundown_items_legacy')
    op.drop_table('rundown_items_legacy')
    op.drop_index(op.f('ix_episodes_legacy_episode_number'), table_name='episodes_legacy')
    op.drop_index(op.f('ix_episodes_legacy_id'), table_name='episodes_legacy')
    op.drop_table('episodes_legacy')
    op.drop_index(op.f('ix_asset_id_registry_asset_id'), table_name='asset_id_registry')
    op.drop_index(op.f('ix_asset_id_registry_entity_type'), table_name='asset_id_registry')
    op.drop_index(op.f('ix_asset_id_registry_id'), table_name='asset_id_registry')
    op.drop_table('asset_id_registry')
    op.drop_index(op.f('ix_cue_blocks_asset_id'), table_name='cue_blocks')
    op.drop_index(op.f('ix_cue_blocks_id'), table_name='cue_blocks')
    op.drop_index(op.f('ix_cue_blocks_slug'), table_name='cue_blocks')
    op.drop_table('cue_blocks')
    op.alter_column('organizations', 'founded_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('shows', 'host')
    op.drop_column('shows', 'website')
    op.drop_column('shows', 'logo')
    op.drop_column('shows', 'slug')
    op.drop_column('shows', 'schedule')
    op.drop_column('shows', 'poster')
    op.drop_column('shows', 'trailer')
    op.drop_column('shows', 'contact_name')
    op.drop_column('shows', 'format')
    op.drop_column('shows', 'social_links')
    op.drop_column('shows', 'contact_phone')
    op.drop_column('shows', 'contact_email')
    op.drop_column('shows', 'api_keys')
    op.drop_column('shows', 'category')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'profile_picture',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.add_column('shows', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('api_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('format', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('trailer', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('poster', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('schedule', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('logo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('organizations', 'founded_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.create_table('cue_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rundown_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cue_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quote_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attribution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('validated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rundown_item_id'], ['rundown_items.id'], name=op.f('cue_blocks_rundown_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cue_blocks_pkey'))
    )
    op.create_index(op.f('ix_cue_blocks_slug'), 'cue_blocks', ['slug'], unique=False)
    op.create_index(op.f('ix_cue_blocks_id'), 'cue_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_cue_blocks_asset_id'), 'cue_blocks', ['asset_id'], unique=False)
    op.create_table('asset_id_registry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_table', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('request_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('initial_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_id_registry_pkey'))
    )
    op.create_index(op.f('ix_asset_id_registry_id'), 'asset_id_registry', ['id'], unique=False)
    op.create_index(op.f('ix_asset_id_registry_entity_type'), 'asset_id_registry', ['entity_type'], unique=False)
    op.create_index(op.f('ix_asset_id_registry_asset_id'), 'asset_id_registry', ['asset_id'], unique=True)
    op.create_table('episodes_legacy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('episodes_legacy_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('episode_number', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('airdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('guest', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_compiled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_quote_extraction', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('episode_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='episodes_legacy_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_episodes_legacy_id'), 'episodes_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_legacy_episode_number'), 'episodes_legacy', ['episode_number'], unique=True)
    op.create_table('rundown_items_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resources', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guests', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes_legacy.id'], name=op.f('rundown_items_legacy_episode_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rundown_items_legacy_pkey'))
    )
    op.create_index(op.f('ix_rundown_items_legacy_slug'), 'rundown_items_legacy', ['slug'], unique=False)
    op.create_index(op.f('ix_rundown_items_legacy_id'), 'rundown_items_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_rundown_items_legacy_asset_id'), 'rundown_items_legacy', ['asset_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('settings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('extracted_quotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quote_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attribution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source_line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes_legacy.id'], name=op.f('extracted_quotes_episode_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extracted_quotes_pkey'))
    )
    op.create_index(op.f('ix_extracted_quotes_slug'), 'extracted_quotes', ['slug'], unique=False)
    op.create_index(op.f('ix_extracted_quotes_quote_id'), 'extracted_quotes', ['quote_id'], unique=False)
    op.create_index(op.f('ix_extracted_quotes_id'), 'extracted_quotes', ['id'], unique=False)
    op.create_table('blueprint_templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('blueprint_templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('template_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blueprint_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_blueprint_templates_template_type'), 'blueprint_templates', ['template_type'], unique=False)
    op.create_index(op.f('ix_blueprint_templates_name'), 'blueprint_templates', ['name'], unique=True)
    op.create_table('blueprint_nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('node_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['blueprint_nodes.id'], name=op.f('blueprint_nodes_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['blueprint_templates.id'], name=op.f('blueprint_nodes_template_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blueprint_nodes_pkey'))
    )
    op.create_index(op.f('ix_blueprint_nodes_template_id'), 'blueprint_nodes', ['template_id'], unique=False)
    op.create_index(op.f('ix_blueprint_nodes_parent_id'), 'blueprint_nodes', ['parent_id'], unique=False)
    op.create_table('episode_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('episode_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('scaffold_episodes_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('scaffold_episodes_organization_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['blueprint_templates.id'], name=op.f('scaffold_episodes_template_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('scaffold_episodes_pkey'))
    )
    op.create_index(op.f('ix_scaffold_episodes_status'), 'episode_templates', ['status'], unique=False)
    op.create_index(op.f('ix_scaffold_episodes_organization_id'), 'episode_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scaffold_episodes_episode_number'), 'episode_templates', ['episode_number'], unique=True)
    op.create_table('asset_id_pending_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pending_asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('delivered', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_id_pending_messages_pkey'))
    )
    op.create_index(op.f('ix_asset_id_pending_messages_pending_asset_id'), 'asset_id_pending_messages', ['pending_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_id_pending_messages_id'), 'asset_id_pending_messages', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes_legacy.id'], name=op.f('assets_episode_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_index(op.f('ix_assets_slug'), 'assets', ['slug'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes_legacy.id'], name=op.f('processing_jobs_episode_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_jobs_pkey'))
    )
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_table('asset_id_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_bidirectional', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_id_relationships_pkey'))
    )
    op.create_index(op.f('ix_asset_id_relationships_target_asset_id'), 'asset_id_relationships', ['target_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_id_relationships_source_asset_id'), 'asset_id_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_id_relationships_relationship_type'), 'asset_id_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_asset_id_relationships_id'), 'asset_id_relationships', ['id'], unique=False)
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_permission_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_id'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_table('user_groups')
    op.drop_table('role_permissions')
    op.drop_table('group_roles')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rbac_audit_log_id'), table_name='rbac_audit_log')
    op.drop_index(op.f('ix_rbac_audit_log_created_at'), table_name='rbac_audit_log')
    op.drop_index(op.f('ix_rbac_audit_log_action'), table_name='rbac_audit_log')
    op.drop_table('rbac_audit_log')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_index(op.f('ix_groups_organization_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###