<template>
  <v-dialog :model-value="show" @update:model-value="$emit('update:show', $event)" max-width="700" persistent>
    <v-card class="fsq-modal-card">
      <v-card-title class="d-flex align-center bg-lime text-black">
        <v-icon class="mr-2">mdi-format-quote-close</v-icon>
        Add Full-Screen Quote (FSQ)
        <v-spacer></v-spacer>
        <v-btn icon size="small" variant="text" @click="cancel" color="black">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-card-title>
      
      <v-card-text class="pb-2 compact-fsq-modal">
        <v-form ref="fsqFormRef" v-model="formValid">
          <!-- Quote Text -->
          <v-textarea
            ref="quoteFieldRef"
            v-model="quote"
            label="Quote Text"
            placeholder="Enter the quote text..."
            variant="outlined"
            rows="6"
            auto-grow
            :rules="quoteRules"
            required
            :class="[
              'mb-2',
              {
                'ai-analyzing': aiState === 'analyzing',
                'ai-rejected': aiState === 'rejected',
                'ai-approved': aiState === 'approved',
                'ai-auto': aiState === 'auto'
              }
            ]"
            density="compact"
            @paste="handleQuotePaste"
            @input="handleQuoteInput"
          >
            <template #append-inner>
              <v-icon v-if="aiState === 'analyzing'" color="amber" size="small" class="rotating">mdi-brain</v-icon>
              <v-icon v-else-if="aiState === 'rejected'" color="error" size="small">mdi-alert-circle</v-icon>
              <v-icon v-else-if="aiState === 'approved'" color="success" size="small">mdi-check-circle</v-icon>
              <v-icon v-else-if="aiState === 'auto'" color="info" size="small">mdi-robot</v-icon>
              <span v-else class="text-error">*</span>
            </template>
            <template #messages>
              <div v-if="aiMessage" class="ai-feedback-message" :class="`ai-message-${aiState}`">
                <div class="d-flex align-center justify-space-between">
                  <div class="flex-grow-1">
                    {{ aiMessage }}
                    <!-- Debug: {{ aiState }} -->
                  </div>
                  <div v-if="aiActionPending" class="ai-action-buttons ml-2">
                    <v-btn
                      size="x-small"
                      color="success"
                      variant="text"
                      @click="acceptAIChange"
                      class="mr-1"
                    >
                      Accept
                    </v-btn>
                    <v-btn
                      size="x-small"
                      color="error"
                      variant="text"
                      @click="rejectAIChange"
                    >
                      Revert
                    </v-btn>
                  </div>
                </div>
              </div>
            </template>
          </v-textarea>

          <!-- AI Generation Credits (very small text) -->
          <div v-if="aiGenerationInfo" class="ai-credit-text mt-n2 mb-2">
            Generated by: {{ aiGenerationInfo.model }} | {{ aiGenerationInfo.timestamp }}
          </div>

          <!-- Word count display - directly under quote, bottom left -->
          <div v-if="quote && quote.length > 0" class="word-count-display mb-2">
            WORDCOUNT: <strong>{{ quote.trim().split(/\s+/).filter(w => w.length > 0).length }}</strong>
          </div>

          <!-- Spacing after AI credits -->
          <div v-if="aiGenerationInfo" style="margin-bottom: 1em;"></div>

          <!-- Collapsible AI Recommendation Section -->
          <!-- AI Recommendation Banner (when recommendations exist but panel is collapsed) -->
          <v-alert
            v-if="splitRecommendations && splitRecommendations.length > 1 && aiRecommendationExpanded.length === 0"
            type="error"
            variant="tonal"
            prominent
            class="mb-2 ai-recommendation-banner"
            @click="aiRecommendationExpanded = [0]"
            style="cursor: pointer; border: 2px dashed #F44336 !important;"
          >
            <div class="d-flex align-center justify-space-between">
              <div class="d-flex align-center">
                <v-icon class="mr-2" size="large">mdi-alert-circle-outline</v-icon>
                <div>
                  <div class="text-h6 mb-1">AI Review Required</div>
                  <div><strong>{{ splitRecommendations.length }} split recommendations</strong> — Click to expand and review</div>
                </div>
              </div>
              <v-icon size="x-large">mdi-chevron-down</v-icon>
            </div>
          </v-alert>

          <v-expansion-panels
            v-if="splitRecommendations && splitRecommendations.length > 1"
            v-model="aiRecommendationExpanded"
            class="mb-3 ai-recommendation-panel"
            :class="{
              'ai-panel-analyzing': aiState === 'analyzing',
              'ai-panel-rejected': aiState === 'rejected',
              'ai-panel-approved': aiState === 'approved',
              'ai-panel-auto': aiState === 'auto'
            }"
          >
            <v-expansion-panel>
              <v-expansion-panel-title class="ai-recommendation-header">
                <div class="d-flex align-center w-100">
                  <v-icon class="mr-2" color="info">mdi-robot</v-icon>
                  <div class="d-flex flex-column">
                    <div>
                      <strong>AI Recommendation:</strong>
                      <span class="ml-1" v-if="aiRecommendationExpanded.length === 0">Click to expand</span>
                      <span class="ml-1" v-else>{{ splitRecommendations.length }} split segments suggested</span>
                    </div>
                    <div class="text-caption text-grey" style="font-size: 0.65rem; margin-top: -2px;">
                      {{ aiGenerationInfo?.model || 'Qwen2.5-Coder' }}
                    </div>
                  </div>
                </div>
              </v-expansion-panel-title>
              <v-expansion-panel-text>
                <div class="ai-recommendation-content">
                  <div class="text-body-2 mb-2">
                    <strong>{{ aiGenerationInfo?.model || 'Qwen2.5-Coder' }}</strong> has determined this quote should be split into
                    <strong>{{ splitRecommendations.length }} individual full-screen graphics</strong>.
                  </div>
                  <div class="text-body-2 mt-3 mb-2">
                    <strong>Recommended split points:</strong>
                  </div>
                  <div v-for="(segment, index) in splitRecommendations" :key="index" class="split-segment mb-2">
                    <v-chip size="small" color="info" class="mr-2">{{ index + 1 }}</v-chip>
                    <span class="segment-text">"{{ segment }}"</span>
                  </div>
                  <v-divider class="my-3"></v-divider>
                  <div class="text-caption mb-3">
                    Each split will create a consecutive cue block with individual AssetID, ready for media conversion once validated.
                  </div>
                  <div class="d-flex gap-2 mt-2">
                    <v-btn
                      color="info"
                      variant="elevated"
                      prepend-icon="mdi-check"
                      @click="acceptAIRecommendation"
                    >
                      Insert {{ splitRecommendations.length }} Split Quotes
                    </v-btn>
                    <v-btn
                      color="secondary"
                      variant="outlined"
                      prepend-icon="mdi-refresh"
                      @click="suggestDifferentSplit"
                      :loading="aiAnalyzing"
                    >
                      Suggest a Different Split
                    </v-btn>
                  </div>
                </div>
              </v-expansion-panel-text>
            </v-expansion-panel>
          </v-expansion-panels>

          <!-- Attribution inline -->
          <v-row dense class="mb-2" justify="end">
            <v-col cols="7">
              <v-text-field
                v-model="source"
                label="Source / Attribution"
                placeholder="e.g., John Doe, CEO"
                variant="outlined"
                :required="includeAttribution"
                density="compact"
                :disabled="!includeAttribution"
                :color="sourceAutopopulated ? 'error' : 'primary'"
                class="source-attribution-field"
                hide-details
              >
                <template #append-inner>
                  <span v-if="includeAttribution" class="text-error">*</span>
                </template>
              </v-text-field>
            </v-col>
            <v-col cols="5" class="d-flex align-center">
              <v-radio-group v-model="includeAttribution" inline density="compact" hide-details>
                <v-radio label="Include" :value="true" density="compact"></v-radio>
                <v-radio label="Omit" :value="false" density="compact"></v-radio>
              </v-radio-group>
            </v-col>
          </v-row>

          <!-- Preview -->
          <div class="quote-preview-container mb-3">
            <video
              class="preview-video-background"
              autoplay
              loop
              muted
              playsinline
              src="/assets/preview-background.mp4"
            >
            </video>
            <div class="black-bar-overlay"></div>
            <div class="quote-preview" :style="previewStyle">
              <div class="quote-text" :style="quoteTextStyle" v-html="formattedQuotePreview"></div>
              <div v-if="includeAttribution" class="quote-source" :style="quoteSourceStyle">— {{ source || 'Source' }}</div>
            </div>
          </div>

          <!-- Quote Style Options - Below Preview -->
          <v-row dense class="mb-2" style="margin-top: 2em;">
            <v-col cols="6">
              <v-select
                v-model="quoteStyle"
                :items="styleOptions"
                label="Alignment"
                variant="outlined"
                density="compact"
              />
            </v-col>
            <v-col cols="6">
              <v-select
                v-model="fontFamily"
                :items="fontOptions"
                label="Font"
                variant="outlined"
                density="compact"
              />
            </v-col>
          </v-row>

          <!-- Font Size Slider on its own line -->
          <v-row dense class="mb-2">
            <v-col cols="12">
              <v-slider
                v-model="fontSize"
                label="Font Size"
                min="10"
                max="40"
                step="0.5"
                thumb-label
                density="compact"
                class="font-size-slider"
              >
                <template v-slot:append>
                  <v-chip size="small" color="lime">
                    {{ fontSize }}px
                  </v-chip>
                </template>
              </v-slider>
            </v-col>
          </v-row>

          <!-- Render As -->
          <v-radio-group v-model="renderMode" inline density="compact" class="mb-2" hide-details>
            <template #label>
              <span class="text-caption">Render as:</span>
            </template>
            <v-radio label="Transparent PNG" value="png" density="compact"></v-radio>
            <v-radio label="Composited with video (30s)" value="video" density="compact"></v-radio>
          </v-radio-group>

          <!-- Error Display -->
          <v-alert
            v-if="error"
            type="error"
            variant="tonal"
            class="mb-3"
          >
            {{ error }}
          </v-alert>
        </v-form>
      </v-card-text>
      
      <v-card-actions class="px-6 pb-4 d-flex">
        <v-btn color="secondary" @click="cancel" variant="outlined">
          Cancel All
        </v-btn>
        <v-spacer></v-spacer>
        <v-btn
          v-if="splitRecommendations && splitRecommendations.length > 1"
          color="success"
          @click="acceptAIRecommendation"
          :disabled="!formValid"
          :loading="loading"
          variant="elevated"
          prepend-icon="mdi-check-circle"
          class="mr-2"
        >
          Accept AI and Insert
        </v-btn>
        <v-btn
          color="deep-purple-darken-2"
          @click="rejectAIRecommendation"
          :disabled="!formValid"
          :loading="loading"
          variant="elevated"
          prepend-icon="mdi-format-quote-close"
        >
          {{ splitRecommendations && splitRecommendations.length > 1 ? 'Reject AI and Insert Original' : 'Insert Quote' }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.fsq-modal-card {
  max-height: 90vh;
  overflow-y: auto;
}

/* Compact FSQ modal styling */
.compact-fsq-modal {
  font-size: 0.9rem;
}

.compact-fsq-modal :deep(.v-label),
.compact-fsq-modal :deep(.v-field-label),
.compact-fsq-modal :deep(.v-input__details),
.compact-fsq-modal :deep(.v-messages) {
  font-size: 0.85rem;
}

/* Move floating labels up by 1em */
:deep(.v-field-label--floating) {
  transform: translateY(-1em) !important;
}

/* Move Source/Attribution floating label up by additional 0.7em (total 1.7em) */
:deep(.v-text-field .v-field-label--floating) {
  transform: translateY(-1.7em) !important;
}

/* AI Processing Visual Feedback - DISTINCTIVE STYLES */
/* Gold DASHED border: AI considering something about this field (thinking/analyzing) */
.ai-analyzing :deep(.v-field) {
  border: 2px dashed #FFC107 !important;
  border-radius: 0 !important;
}

.ai-analyzing :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

/* Red DASHED border: Change pending or possible rejection - needs human attention */
.ai-rejected :deep(.v-field) {
  border: 2px dashed #F44336 !important;
  border-radius: 0 !important;
}

.ai-rejected :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

/* Green DASHED border: AI generation approved by user */
.ai-approved :deep(.v-field) {
  border: 2px dashed #4CAF50 !important;
  border-radius: 0 !important;
}

.ai-approved :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

/* Blue DASHED border: AI auto-generation not requiring human approval */
.ai-auto :deep(.v-field) {
  border: 2px dashed #2196F3 !important;
  border-radius: 0 !important;
}

.ai-auto :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

/* Rotating brain icon animation */
.rotating {
  animation: rotate 2s linear infinite;
}

@keyframes rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.quote-preview-container {
  position: relative;
  width: 100%;
  min-height: 400px; /* Larger preview - was aspect-ratio 16/9 */
  border-radius: 0 !important; /* NO ROUNDED CORNERS */
  overflow: hidden;
  background: #000;
}

.preview-video-background {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  z-index: 1;
}

.black-bar-overlay {
  position: absolute;
  top: 10%;
  left: 0;
  width: 100%;
  height: 80%;
  background: rgba(0, 0, 0, 0.6);
  z-index: 2;
}

.quote-preview {
  position: absolute;
  top: 10%;
  left: 0;
  width: 100%;
  height: 80%;
  color: white;
  padding: 10%; /* 10% padding inside black box */
  display: flex;
  flex-direction: column;
  justify-content: center;
  z-index: 3;
  box-sizing: border-box;
}

.quote-text {
  font-size: 1.4rem;
  font-style: italic;
  line-height: 1.4;
  font-family: Georgia, serif;
  flex-grow: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

.quote-source {
  font-size: 1rem;
  font-weight: 500;
  color: #e0e0e0;
  position: absolute;
  bottom: 5px; /* 5px above bottom of black box */
  left: 10%; /* Match parent padding */
  right: 10%; /* Match parent padding */
  text-align: inherit; /* Inherit alignment from parent */
}

.quote-timestamp {
  font-size: 0.85rem;
  color: #b0b0b0;
  font-family: 'Courier New', monospace;
}

/* Responsive typography */
@media (max-width: 600px) {
  .quote-text {
    font-size: 1.2rem;
  }

  .quote-source {
    font-size: 0.9rem;
  }

  .quote-timestamp {
    font-size: 0.8rem;
  }
}

/* Font size slider styling */
.font-size-slider {
  margin-top: 8px;
}

/* Word count display - directly under quote */
.word-count-display {
  font-size: 12px;
  color: #666;
  text-align: left;
  margin-top: 4px;
}

/* AI feedback messages - styled by state */
.ai-feedback-message {
  font-size: 13px;
  padding: 4px 8px;
  margin-top: 4px;
  font-weight: 500;
}

.ai-message-analyzing {
  color: #F57C00; /* Amber/orange for analyzing */
}

.ai-message-rejected {
  color: #D32F2F; /* Red for split recommendation */
}

.ai-message-approved {
  color: #388E3C; /* Green for approved */
}

.ai-message-auto {
  color: #1976D2; /* Blue for auto-corrections */
}

/* AI generation credit text - very small, subtle */
.ai-credit-text {
  font-size: 9px;
  color: #999;
  font-family: 'Courier New', monospace;
  margin-top: -8px;
  margin-bottom: 8px;
  padding-left: 4px;
  opacity: 0.7;
}

/* Split segment styling */
.split-segment {
  background: rgba(33, 150, 243, 0.05);
  padding: 8px 12px;
  border-radius: 0 !important; /* NO ROUNDED CORNERS */
  border-left: 3px solid #2196F3;
}

.segment-text {
  font-style: italic;
  color: #424242;
  line-height: 1.5;
}

/* AI Recommendation Panel styling - matches text field border color */
.ai-recommendation-panel {
  border-radius: 0 !important; /* NO ROUNDED CORNERS */
}

/* Gold panel for analyzing state */
.ai-recommendation-panel.ai-panel-analyzing {
  border: 2px dashed #FFC107;
}

.ai-recommendation-panel.ai-panel-analyzing .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(255, 193, 7, 0.1) 0%, rgba(255, 193, 7, 0.05) 100%);
}

/* Red panel for rejected state */
.ai-recommendation-panel.ai-panel-rejected {
  border: 2px dashed #F44336;
}

.ai-recommendation-panel.ai-panel-rejected .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(244, 67, 54, 0.1) 0%, rgba(244, 67, 54, 0.05) 100%);
}

/* Green panel for approved state */
.ai-recommendation-panel.ai-panel-approved {
  border: 2px dashed #4CAF50;
}

.ai-recommendation-panel.ai-panel-approved .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(76, 175, 80, 0.1) 0%, rgba(76, 175, 80, 0.05) 100%);
}

/* Blue panel for auto state */
.ai-recommendation-panel.ai-panel-auto {
  border: 2px dashed #2196F3;
}

.ai-recommendation-panel.ai-panel-auto .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(33, 150, 243, 0.1) 0%, rgba(33, 150, 243, 0.05) 100%);
}

.ai-recommendation-header {
  font-weight: 600;
}

.ai-recommendation-content {
  padding: 12px 0;
}

/* GLOBAL: NO ROUNDED CORNERS ON ANYTHING */
.fsq-modal-card :deep(.v-field),
.fsq-modal-card :deep(.v-text-field),
.fsq-modal-card :deep(.v-textarea),
.fsq-modal-card :deep(.v-card),
.fsq-modal-card :deep(.v-alert),
.fsq-modal-card :deep(.v-btn),
.fsq-modal-card :deep(.v-expansion-panel),
.fsq-modal-card :deep(.v-chip) {
  border-radius: 0 !important;
}
</style>

<script>
import axios from 'axios'
import { useLLM } from '@/composables/useLLM'

export default {
  name: 'FsqModal',
  props: {
    show: { type: Boolean, required: true },
    currentEpisode: { type: String, default: '' }
  },
  emits: ['update:show', 'submit'],
  data() {
    return {
      formValid: false,
      loading: false,
      error: '',
      quote: '',
      source: '',
      includeAttribution: true,
      quoteStyle: 'left',
      fontFamily: 'sans-serif',
      fontSize: 25,
      renderMode: 'png',
      duration: '00:00:05:00',
      lastSubmittedSource: '', // Store last submitted source
      sourceAutopopulated: false, // Track if source was autopopulated
      aiAnalyzing: false, // Track if AI is analyzing the quote
      analyzeTimeout: null, // Debounce timeout for quote analysis
      aiState: null, // 'analyzing', 'rejected', 'approved', 'auto', or null
      aiMessage: '', // AI feedback message to display
      aiActionPending: false, // Whether AI action needs user accept/reject
      aiPreviousQuote: '', // Store quote before AI changes for revert
      splitRecommendations: null, // Store AI split recommendations
      aiGenerationInfo: null, // { model: 'qwen2.5-coder:7b', timestamp: '2025-10-03 14:23:15' }
      aiRecommendationExpanded: [] // Controls expansion panel (empty array = collapsed by default)
    }
  },
  setup() {
    const { intelligentQuoteSplit, normalizeNestedQuotes } = useLLM()
    return { intelligentQuoteSplit, normalizeNestedQuotes }
  },
  watch: {
    show(newVal) {
      if (newVal) {
        // Autopopulate source field with last submitted value
        if (this.lastSubmittedSource && !this.source) {
          this.source = this.lastSubmittedSource
          this.sourceAutopopulated = true
        }

        // Focus the quote field when modal opens
        this.$nextTick(() => {
          if (this.$refs.quoteFieldRef) {
            this.$refs.quoteFieldRef.focus()
          }
        })
      }
    },
    // Clear autopopulate flag when user modifies source field
    source(newVal) {
      if (this.sourceAutopopulated && newVal !== this.lastSubmittedSource) {
        this.sourceAutopopulated = false
      }
    }
  },
  computed: {
    quoteRules() {
      return [
        v => !!v || 'Quote text is required',
        v => !v || v.length >= 10 || 'Quote must be at least 10 characters'
      ]
    },
    sourceRules() {
      return [
        v => !!v || 'Source/attribution is required',
        v => !v || v.length <= 100 || 'Source must be 100 characters or less'
      ]
    },
    styleOptions() {
      return [
        { title: 'Centered', value: 'centered' },
        { title: 'Left Aligned', value: 'left' },
        { title: 'Right Aligned', value: 'right' },
        { title: 'Large Text', value: 'large' },
        { title: 'Elegant', value: 'elegant' }
      ]
    },
    durationOptions() {
      return [
        { title: '3 seconds', value: '00:00:03:00' },
        { title: '5 seconds', value: '00:00:05:00' },
        { title: '7 seconds', value: '00:00:07:00' },
        { title: '10 seconds', value: '00:00:10:00' },
        { title: '15 seconds', value: '00:00:15:00' },
        { title: 'Custom', value: 'custom' }
      ]
    },
    fontOptions() {
      return [
        { title: 'Sans Serif (Helvetica)', value: 'sans-serif' },
        { title: 'Serif (Georgia)', value: 'serif' },
        { title: 'Monospace (Courier)', value: 'monospace' }
      ]
    },
    previewStyle() {
      return {
        textAlign: this.quoteStyle === 'centered' ? 'center' :
                  this.quoteStyle === 'left' ? 'left' :
                  this.quoteStyle === 'right' ? 'right' : 'center'
      }
    },
    quoteTextStyle() {
      const fontMap = {
        'sans-serif': 'Helvetica, Arial, sans-serif',
        'serif': 'Georgia, "Times New Roman", serif',
        'monospace': '"Courier New", Courier, monospace'
      }
      return {
        fontFamily: fontMap[this.fontFamily] || fontMap['sans-serif'],
        fontSize: `${this.fontSize}px`
      }
    },
    quoteSourceStyle() {
      const fontMap = {
        'sans-serif': 'Helvetica, Arial, sans-serif',
        'serif': 'Georgia, "Times New Roman", serif',
        'monospace': '"Courier New", Courier, monospace'
      }
      return {
        fontFamily: fontMap[this.fontFamily] || fontMap['sans-serif']
      }
    },
    formattedQuotePreview() {
      const rawText = this.quote || 'Quote text will appear here...';

      // Step 1: Decode any stored escape sequences first
      const decoded = this.decodeQuoteText(rawText);

      // Step 2: Escape for safe HTML display
      const escaped = decoded
        .replace(/&/g, '&amp;')           // Escape ampersands first
        .replace(/"/g, '&quot;')           // Escape all double quotes
        .replace(/'/g, '&#39;')            // Escape all single quotes
        .replace(/</g, '&lt;')             // Escape less-than
        .replace(/>/g, '&gt;')             // Escape greater-than
        .replace(/\n/g, '<br>');           // Actual newlines to <br>

      return '"' + escaped + '"';
    }
  },
  mounted() {
    // Add ESC key listener
    document.addEventListener('keydown', this.handleKeydown)
  },
  beforeUnmount() {
    document.removeEventListener('keydown', this.handleKeydown)
  },
  methods: {
    /**
     * Detect if quote text has nested quotes (quotes within quotes)
     * @param {string} text - The quote text to analyze
     * @returns {boolean} - True if nested quotes detected
     */
    hasNestedQuotes(text) {
      if (!text) return false

      // Decode first to check actual quote characters
      const decoded = this.decodeQuoteText(text)

      // Count different types of quotes
      const doubleQuotes = (decoded.match(/"/g) || []).length
      const singleQuotes = (decoded.match(/'/g) || []).length

      // Filter out apostrophes (single quotes followed by letters or preceded by letters)
      const apostrophes = (decoded.match(/[a-z]'|'[a-z]/gi) || []).length

      // Actual single quotes = total single quotes - apostrophes
      const actualSingleQuotes = singleQuotes - apostrophes

      // Nested quotes exist if:
      // 1. We have both double and single quotes (mixing styles)
      // 2. OR we have multiple pairs of the same type (more than 2 of same quote mark)
      const hasMixedQuotes = doubleQuotes > 0 && actualSingleQuotes > 0
      const hasMultipleDoubles = doubleQuotes > 2 // More than one pair
      const hasMultipleSingles = actualSingleQuotes > 2

      const hasNesting = hasMixedQuotes || hasMultipleDoubles || hasMultipleSingles

      if (hasNesting) {
        console.log('🔍 Nested quotes detected:', {
          text: decoded,
          doubleQuotes,
          singleQuotes,
          apostrophes,
          actualSingleQuotes,
          hasMixedQuotes,
          hasMultipleDoubles,
          hasMultipleSingles
        })
      }

      return hasNesting
    },

    /**
     * Decode stored escape sequences and HTML entities
     * This handles quotes that may have been stored with escape sequences like:
     * - &quot; → "
     * - &#39; → '
     * - &amp; → &
     * - \" → "
     * - \' → '
     * - \n → newline
     */
    decodeQuoteText(text) {
      if (!text) return text

      let decoded = text
        // First decode HTML entities
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        // Then decode backslash escape sequences
        .replace(/\\"/g, '"')
        .replace(/\\'/g, "'")
        .replace(/\\n/g, '\n')
        .replace(/\\r/g, '\r')
        .replace(/\\t/g, '\t')
        .replace(/\\\\/g, '\\') // Double backslash last

      return decoded
    },

    handleKeydown(event) {
      if (event.key === 'Escape' && this.show) {
        this.cancel()
      }
    },

    async handleQuotePaste() {
      // Triggered immediately on paste
      console.log('📋 Paste detected, waiting for v-model update...')

      // Wait for v-model to update with multiple attempts
      await this.$nextTick()

      // Give a small delay for paste to fully populate
      await new Promise(resolve => setTimeout(resolve, 50))

      console.log('📋 Quote pasted (length: ' + this.quote.length + '), starting AI analysis...')

      // Only analyze if we have content
      if (this.quote && this.quote.length > 20) {
        await this.analyzeQuote()
      } else {
        console.log('⏭️ Paste content too short or empty, skipping AI analysis')
      }
    },

    handleQuoteInput() {
      // Clear AI state when user starts typing again (but not messages or pending state)
      if (this.aiState && this.aiState !== 'analyzing' && !this.aiActionPending) {
        this.aiState = null
        this.aiMessage = ''
        this.splitRecommendations = null
        this.aiGenerationInfo = null
      }

      // Don't re-analyze if there's a pending action waiting for user
      if (this.aiActionPending) {
        return
      }

      // Debounce input changes - give user time to finish typing
      clearTimeout(this.analyzeTimeout)
      this.analyzeTimeout = setTimeout(() => {
        if (this.quote.length > 20) {
          console.log('🤖 Triggering AI quote analysis after typing pause...')
          this.analyzeQuote()
        }
      }, 2000) // 2 second debounce - faster response
    },

    async analyzeQuote() {
      if (!this.quote || this.quote.length < 20) {
        console.log('⏭️ Quote too short for AI analysis (< 20 chars)')
        return
      }

      console.log('🤖 Starting AI quote analysis...')
      this.aiAnalyzing = true
      this.aiState = 'analyzing'
      this.aiMessage = 'AI is analyzing your quote...'

      try {
        // STEP 1: Decode escape sequences first
        let workingQuote = this.decodeQuoteText(this.quote)
        if (workingQuote !== this.quote) {
          console.log('🔓 Decoded escape sequences:', { before: this.quote, after: workingQuote })
          this.aiPreviousQuote = this.quote // Save for revert
          this.quote = workingQuote
          this.aiState = 'auto'
          this.aiMessage = 'AI decoded escape sequences in your quote text'
          this.aiActionPending = true
          return // Wait for user to accept/reject
        }

        // STEP 2: Check for nested quotes and normalize if needed
        if (this.hasNestedQuotes(workingQuote)) {
          console.log('📝 Nested quotes detected, normalizing...')
          this.aiMessage = 'Nested quotes detected - normalizing quotation marks...'
          const normalized = await this.normalizeNestedQuotes(workingQuote)

          // If normalization changed the text, update the quote field
          if (normalized !== this.quote) {
            console.log('✨ Quote normalized:', { before: this.quote, after: normalized })
            this.aiPreviousQuote = this.quote // Save for revert
            this.quote = normalized
            workingQuote = normalized

            // Flash blue to indicate AI auto-correction
            this.aiState = 'auto'
            this.aiMessage = 'AI corrected quotation mark nesting to follow American English style'
            this.aiActionPending = true
            return // Wait for user to accept/reject
          }
        }

        // Continue to split analysis
        this.aiState = 'analyzing'
        this.aiMessage = 'AI is checking if quote needs to be split...'

        // STEP 3: Load generation settings from backend
        console.log('📥 Loading generation settings from backend...')
        const settingsResponse = await axios.get('/api/settings/', {
          headers: {
            'X-API-Key': 'FDT5WyO7S2DbBifbDUEsd1H8cmZTT3_qpJXtb3c7qaY'
          }
        })

        const settings = settingsResponse.data.generation || {}
        console.log('⚙️ Generation settings:', {
          maxLines: settings.fsq_max_lines || 4,
          charsPerLine: settings.fsq_chars_per_line || 70,
          fontSize: settings.default_font_size || '19px'
        })

        // STEP 4: Call AI for split analysis with decoded and normalized quote
        console.log('🧠 Calling intelligentQuoteSplit()...')
        const segments = await this.intelligentQuoteSplit(workingQuote, {
          maxLines: settings.fsq_max_lines || 4,
          charsPerLine: settings.fsq_chars_per_line || 70,
          fontSize: settings.default_font_size || '19px'
        })

        console.log('✅ AI quote analysis result:', segments)

        // Store AI generation info
        const now = new Date()
        this.aiGenerationInfo = {
          model: 'qwen2.5-coder:7b',
          timestamp: now.toLocaleString('en-US', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
          })
        }

        // If split into multiple segments, show review modal (red state = requires changes)
        if (segments.length > 1) {
          this.aiState = 'rejected'
          this.aiMessage = `AI recommends splitting this quote into ${segments.length} separate FSQ cues`
          this.splitRecommendations = segments

          // Keep panel collapsed - let invitation banner prompt user to expand
          this.aiRecommendationExpanded = [] // Collapsed by default

          console.log(`✂️ AI recommends splitting into ${segments.length} segments`)
          console.log('📋 Recommendation panel ready - invitation banner will prompt user to expand')
          console.log('💬 AI Message set to:', this.aiMessage)
        } else {
          // Quote fits as-is (green state = approved)
          this.aiState = 'approved'
          this.aiMessage = 'AI approved - quote fits perfectly as a single full-screen graphic'
          this.splitRecommendations = null // Clear any previous recommendations
          this.aiRecommendationExpanded = [] // Collapse panel

          console.log('✅ AI approved - quote fits as single FSQ')
          console.log('💬 AI Message set to:', this.aiMessage)
          console.log('🎨 AI State set to:', this.aiState)
          // Keep green border visible - don't auto-clear
        }
      } catch (error) {
        console.error('Quote analysis failed:', error)
        this.aiState = null
        this.aiMessage = `Analysis failed: ${error.message || 'Unknown error'}`
      } finally {
        this.aiAnalyzing = false
      }
    },

    // Generate a slug from quote text using AI-friendly approach
    generateSlugFromQuote(quoteText) {
      return quoteText
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '') // Remove punctuation except spaces and hyphens
        .replace(/\s+/g, '-') // Convert spaces to hyphens
        .replace(/-+/g, '-') // Collapse multiple hyphens
        .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
        .substring(0, 50) // Limit length
        || 'fsq-quote'
    },

    // Split long quotes into multiple segments at sentence boundaries
    splitQuoteIntoSegments(quoteText, maxLength = 300) {
      if (quoteText.length <= maxLength) {
        return [quoteText]
      }

      const segments = []
      let currentSegment = ''

      // Split by sentences (periods, exclamation marks, question marks)
      const sentences = quoteText.match(/[^.!?]+[.!?]+|[^.!?]+$/g) || [quoteText]

      for (const sentence of sentences) {
        if ((currentSegment + sentence).length <= maxLength) {
          currentSegment += sentence
        } else {
          if (currentSegment) {
            segments.push(currentSegment.trim())
          }
          currentSegment = sentence
        }
      }

      if (currentSegment) {
        segments.push(currentSegment.trim())
      }

      return segments
    },

    async submit() {
      // Validate form
      const isValid = await this.$refs.fsqFormRef.validate()
      console.log('Form validation result:', isValid)
      if (!isValid) {
        console.warn('Form validation failed')
        return
      }

      this.loading = true
      this.error = ''

      try {
        const currentEpisode = this.$route.params.episode || this.currentEpisode

        if (!currentEpisode) {
          throw new Error('No episode ID available')
        }

        // Use AI split recommendations if available, otherwise use legacy split
        const quoteSegments = this.splitRecommendations && this.splitRecommendations.length > 0
          ? this.splitRecommendations
          : [this.quote.trim()]

        console.log(`Creating ${quoteSegments.length} FSQ cue(s)`)

        // Store the source for next time if attribution is included
        if (this.includeAttribution && this.source.trim()) {
          this.lastSubmittedSource = this.source.trim()
        }

        // Process each segment
        for (let i = 0; i < quoteSegments.length; i++) {
          const segment = quoteSegments[i]
          const isMultipart = quoteSegments.length > 1

          // Generate AssetID for this FSQ cue segment
          const assetId = await this.generateAssetId()

          // Auto-generate slug from quote text
          const baseSlug = this.generateSlugFromQuote(segment)
          const slug = isMultipart ? `${baseSlug}-part-${i + 1}` : baseSlug

          console.log(`Creating FSQ cue ${i + 1}/${quoteSegments.length} (media generation deferred)...`)

          // NOTE: Media generation is now deferred to batch processing
          // The FSQ PNG will be generated later via the batch rendering system
          // For now, just create the cue block with metadata

          // Calculate word count for this segment
          const wordCount = segment.trim().split(/\s+/).filter(word => word.length > 0).length;

          // Create the FSQ cue data without media URL (will be generated later)
          // Store quote with decoded text (clean, no escape sequences)
          const cleanQuote = this.decodeQuoteText(segment);

          const cueData = {
            type: 'FSQ',
            assetId: assetId,
            slug: slug,
            quote: cleanQuote, // Store decoded text
            style: this.quoteStyle,
            fontFamily: this.fontFamily,
            fontSize: this.fontSize,
            renderMode: this.renderMode,
            duration: this.duration,
            wordCount: wordCount,
            part: isMultipart ? `${i + 1}x${quoteSegments.length}` : '1x1'
            // mediaUrl: null  // Will be populated during batch render
          }

          // Only include source if attribution is enabled
          if (this.includeAttribution && this.source.trim()) {
            cueData.source = this.source.trim()
          }

          console.log(`Creating FSQ cue ${i + 1} with asset:`, cueData)

          // Emit the cue creation
          this.$emit('submit', cueData)

          // Small delay between multiple segments to allow placement
          if (i < quoteSegments.length - 1) {
            await new Promise(resolve => setTimeout(resolve, 500))
          }
        }

        // Reset and close
        this.reset()
        this.$emit('update:show', false)

      } catch (error) {
        console.error('Error creating FSQ cue:', error)
        this.error = error.response?.data?.detail || 'Failed to create quote cue. Please try again.'
      } finally {
        this.loading = false
      }
    },
    cancel() {
      this.$emit('update:show', false)
      this.reset()
    },
    async generateAssetId() {
      try {
        console.log('Requesting AssetID for FSQ cue')

        // Create a slug from the quote text
        const slug = this.quote.trim()
          .toLowerCase()
          .replace(/[^a-z0-9\s-]/g, '') // Remove punctuation except spaces and hyphens
          .replace(/\s+/g, '-') // Convert spaces to hyphens
          .replace(/-+/g, '-') // Collapse multiple hyphens
          .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
          .substring(0, 50) // Limit length

        // Create form data for the API call
        const formData = new FormData()
        formData.append('slug', slug || 'fsq-quote')
        formData.append('type', 'fsq')

        // Try the legacy endpoint first (most reliable)
        const response = await axios.post('/assetid/generate-legacy', formData, {
          headers: {
            'Accept': 'application/json',
            'X-API-Key': 'FDT5WyO7S2DbBifbDUEsd1H8cmZTT3_qpJXtb3c7qaY'
          }
        })

        if (response.data && response.data.id) {
          console.log('Successfully generated AssetID:', response.data.id)
          return response.data.id
        } else {
          throw new Error('Invalid response format: missing id field')
        }
      } catch (error) {
        console.warn('AssetID generation failed, using fallback:', error)

        // Fallback to local generation if server fails
        const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
        let result = 'LOCAL_FSQ_'
        for (let i = 0; i < 8; i++) {
          result += chars.charAt(Math.floor(Math.random() * chars.length))
        }
        console.log('Generated local fallback AssetID:', result)
        return result
      }
    },
    reset() {
      this.quote = ''
      this.source = ''
      this.sourceAutopopulated = false
      this.includeAttribution = true
      this.quoteStyle = 'left'
      this.fontFamily = 'sans-serif'
      this.fontSize = 25
      this.duration = '00:00:05:00'
      this.error = ''
      this.loading = false
      this.aiState = null
      this.splitRecommendations = null
      this.aiGenerationInfo = null

      // Reset form validation
      this.$nextTick(() => {
        if (this.$refs.fsqFormRef) {
          this.$refs.fsqFormRef.resetValidation()
        }
      })
    },
    acceptAIChange() {
      // User accepted the AI change
      console.log('✅ User accepted AI change')
      this.aiActionPending = false
      this.aiPreviousQuote = '' // Clear the backup
      this.aiMessage = '' // Clear message
      // Continue with analysis if needed
      this.analyzeQuote()
    },

    rejectAIChange() {
      // User rejected the AI change - revert to previous quote
      console.log('❌ User rejected AI change - reverting')
      this.quote = this.aiPreviousQuote
      this.aiPreviousQuote = ''
      this.aiActionPending = false
      this.aiState = null
      this.aiMessage = ''
    },

    async acceptAIRecommendation() {
      // Accept AI split recommendations and insert them
      // The submit() method already handles splitRecommendations
      console.log('Accepting AI split recommendation and submitting...')
      await this.submit()
    },
    async rejectAIRecommendation() {
      // Reject AI recommendations and insert original quote as single cue
      // Clear split recommendations before submitting
      this.splitRecommendations = null
      this.aiState = null
      this.aiGenerationInfo = null
      await this.submit()
    },
    async suggestDifferentSplit() {
      // Request the AI to suggest an alternative split for the quote
      console.log('Requesting alternative split suggestion...')

      if (!this.quote || this.quote.length < 20) {
        console.warn('Quote too short for alternative split analysis')
        return
      }

      this.aiAnalyzing = true
      this.aiState = 'analyzing'

      try {
        // Load generation settings from backend
        const settingsResponse = await axios.get('/api/settings/', {
          headers: {
            'X-API-Key': 'FDT5WyO7S2DbBifbDUEsd1H8cmZTT3_qpJXtb3c7qaY'
          }
        })

        const settings = settingsResponse.data.generation || {}

        // Call AI with higher temperature for more variation in splits
        const segments = await this.intelligentQuoteSplit(this.quote, {
          maxLines: settings.fsq_max_lines || 4,
          charsPerLine: settings.fsq_chars_per_line || 70,
          fontSize: settings.default_font_size || '19px',
          temperature: 0.5  // Higher temperature for more varied results
        })

        console.log('Alternative AI quote analysis result:', segments)

        // Update AI generation info
        const now = new Date()
        this.aiGenerationInfo = {
          model: 'qwen2.5-coder:7b',
          timestamp: now.toLocaleString('en-US', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
          })
        }

        // Update split recommendations
        if (segments.length > 1) {
          this.aiState = 'rejected'
          this.splitRecommendations = segments
          console.log('New split suggestion:', segments.length, 'segments')
        } else {
          // If AI suggests no split this time, show that
          this.aiState = 'approved'
          this.splitRecommendations = null
          setTimeout(() => {
            this.aiState = null
          }, 2000)
        }
      } catch (error) {
        console.error('Alternative split analysis failed:', error)
        this.aiState = 'rejected'  // Keep current state on error
      } finally {
        this.aiAnalyzing = false
      }
    }
  }
}
</script>
