<template>
  <v-dialog :model-value="show" @update:model-value="$emit('update:show', $event)" max-width="700" persistent>
    <v-card class="fsq-modal-card">
      <v-card-title class="d-flex align-center bg-lime text-black">
        <v-icon class="mr-2">mdi-format-quote-close</v-icon>
        Add Full-Screen Quote (FSQ)
        <v-spacer></v-spacer>
        <v-btn icon size="small" variant="text" @click="cancel" color="black">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-card-title>

      <v-card-text class="pb-2 compact-fsq-modal">
        <v-form ref="fsqFormRef" v-model="formValid">
          <!-- Quote Text -->
          <div class="quote-field-wrapper" style="position: relative;">
            <v-textarea
              ref="quoteFieldRef"
              v-model="quote"
              label="Quote Text"
              placeholder="Enter the quote text..."
              variant="outlined"
              rows="10"
              auto-grow
              :rules="quoteRules"
              required
              :class="[
                'mb-2',
                'large-quote-field',
                {
                  'ai-analyzing': aiState === 'analyzing',
                  'ai-rejected': aiState === 'rejected',
                  'ai-approved': aiState === 'approved',
                  'ai-auto': aiState === 'auto'
                }
              ]"
              density="comfortable"
              @paste="handleQuotePaste"
              @input="handleQuoteInput"
            >
              <template #append-inner>
                <v-icon v-if="aiState === 'analyzing'" color="purple" size="small" class="rotating">mdi-brain</v-icon>
                <v-icon v-else-if="aiState === 'rejected'" color="error" size="small">mdi-alert-circle</v-icon>
                <v-icon v-else-if="aiState === 'approved'" color="success" size="small">mdi-check-circle</v-icon>
                <v-icon v-else-if="aiState === 'auto'" color="info" size="small">mdi-robot</v-icon>
                <span v-else class="text-error">*</span>
              </template>
              <template #messages>
                <div v-if="aiMessage" class="ai-feedback-message" :class="`ai-message-${aiState}`">
                  <div class="d-flex align-center justify-space-between">
                    <div class="flex-grow-1">
                      {{ aiMessage }}
                    </div>
                    <div v-if="aiActionPending" class="ai-action-buttons ml-2">
                      <v-btn
                        size="x-small"
                        color="success"
                        variant="text"
                        @click="acceptAIChange"
                        class="mr-1"
                      >
                        Accept
                      </v-btn>
                      <v-btn
                        size="x-small"
                        color="error"
                        variant="text"
                        @click="rejectAIChange"
                      >
                        Revert
                      </v-btn>
                    </div>
                  </div>
                </div>
              </template>
            </v-textarea>

            <!-- AI Model Badge -->
            <div v-if="aiState" class="ai-model-badge" :class="`badge-${aiState}`">
              <div class="badge-content">
                <div class="badge-service">Ollama</div>
                <div class="badge-model">qwen2.5-coder:7b</div>
              </div>
            </div>
          </div>

          <!-- AI Generation Credits -->
          <div v-if="aiGenerationInfo" class="ai-credit-text mt-n2 mb-2">
            Generated by: {{ aiGenerationInfo.model }} | {{ aiGenerationInfo.timestamp }}
          </div>

          <!-- Word count display -->
          <div v-if="quote && quote.length > 0" class="word-count-display mb-2">
            WORDCOUNT: <strong>{{ quote.trim().split(/\s+/).filter(w => w.length > 0).length }}</strong>
          </div>

          <!-- Spacing after AI credits -->
          <div v-if="aiGenerationInfo" style="margin-bottom: 1em;"></div>

          <!-- AI Recommendation Expansion Panel -->
          <v-expansion-panels
            v-if="splitRecommendations && splitRecommendations.length > 1"
            v-model="aiRecommendationExpanded"
            class="mb-3 ai-recommendation-panel"
            :class="{
              'ai-panel-analyzing': aiState === 'analyzing',
              'ai-panel-rejected': aiState === 'rejected',
              'ai-panel-approved': aiState === 'approved',
              'ai-panel-auto': aiState === 'auto'
            }"
          >
            <v-expansion-panel>
              <v-expansion-panel-title class="ai-recommendation-header">
                <div class="d-flex align-center w-100">
                  <v-icon class="mr-2" color="info">mdi-robot</v-icon>
                  <div class="d-flex flex-column">
                    <div>
                      <strong>AI Recommendation:</strong>
                      <span class="ml-1" v-if="!aiRecommendationExpanded || aiRecommendationExpanded.length === 0">Click to expand</span>
                      <span class="ml-1" v-else>{{ splitRecommendations.length }} split segments suggested</span>
                    </div>
                    <div class="text-caption text-grey" style="font-size: 0.65rem; margin-top: -2px;">
                      {{ aiGenerationInfo?.model || 'Qwen2.5-Coder' }}
                    </div>
                  </div>
                </div>
              </v-expansion-panel-title>
              <v-expansion-panel-text>
                <div class="ai-recommendation-content">
                  <div class="text-body-2 mb-2">
                    <strong>{{ aiGenerationInfo?.model || 'Qwen2.5-Coder' }}</strong> has determined this quote should be split into
                    <strong>{{ splitRecommendations.length }} individual full-screen graphics</strong>.
                  </div>
                  <div class="text-body-2 mt-3 mb-2">
                    <strong>Recommended split points:</strong>
                  </div>
                  <div v-for="(segment, index) in splitRecommendations" :key="index" class="split-segment mb-2">
                    <v-chip size="small" color="info" class="mr-2">{{ index + 1 }}</v-chip>
                    <span class="segment-text">"{{ segment }}"</span>
                  </div>
                  <v-divider class="my-3"></v-divider>
                  <div class="text-caption mb-3">
                    Each split will create a consecutive cue block with individual AssetID, ready for media conversion once validated.
                  </div>
                  <div class="d-flex gap-2 mt-2">
                    <v-btn
                      color="info"
                      variant="elevated"
                      prepend-icon="mdi-check"
                      @click="acceptAIRecommendation"
                    >
                      Insert {{ splitRecommendations.length }} Split Quotes
                    </v-btn>
                    <v-btn
                      color="secondary"
                      variant="outlined"
                      prepend-icon="mdi-refresh"
                      @click="suggestDifferentSplit"
                      :loading="aiAnalyzing"
                    >
                      Suggest a Different Split
                    </v-btn>
                  </div>
                </div>
              </v-expansion-panel-text>
            </v-expansion-panel>
          </v-expansion-panels>

          <!-- Slug Field -->
          <v-text-field
            ref="slugFieldRef"
            v-model="slug"
            label="Slug"
            placeholder="Enter a short slug for this quote..."
            variant="outlined"
            :rules="slugRules"
            required
            density="compact"
            class="mb-2"
            @blur="normalizeSlug"
          >
            <template #append-inner>
              <span class="text-error">*</span>
            </template>
          </v-text-field>

          <!-- Attribution inline -->
          <v-row dense class="mb-2" justify="end">
            <v-col cols="7">
              <v-text-field
                v-model="source"
                label="Source / Attribution"
                placeholder="e.g., John Doe, CEO"
                variant="outlined"
                :required="includeAttribution"
                density="compact"
                :disabled="!includeAttribution"
                :color="sourceAutopopulated ? 'error' : 'primary'"
                class="source-attribution-field"
                hide-details
              >
                <template #append-inner>
                  <span v-if="includeAttribution" class="text-error">*</span>
                </template>
              </v-text-field>
            </v-col>
            <v-col cols="5" class="d-flex align-center">
              <v-radio-group v-model="includeAttribution" inline density="compact" hide-details>
                <v-radio label="Include" :value="true" density="compact"></v-radio>
                <v-radio label="Omit" :value="false" density="compact"></v-radio>
              </v-radio-group>
            </v-col>
          </v-row>

          <!-- Preview -->
          <div class="quote-preview-container mb-3">
            <video
              class="preview-video-background"
              autoplay
              loop
              muted
              playsinline
              src="/assets/preview-background.mp4"
            >
            </video>
            <div class="black-bar-overlay"></div>
            <div class="quote-preview" :style="previewStyle">
              <div class="quote-text" :style="quoteTextStyle" v-html="formattedQuotePreview"></div>
              <div v-if="includeAttribution" class="quote-source" :style="quoteSourceStyle">— {{ source || 'Source' }}</div>
            </div>
          </div>

          <!-- Quote Style Options -->
          <v-row dense class="mb-2" style="margin-top: 2em;">
            <v-col cols="6">
              <v-select
                v-model="quoteStyle"
                :items="styleOptions"
                label="Alignment"
                variant="outlined"
                density="compact"
              />
            </v-col>
            <v-col cols="6">
              <v-select
                v-model="fontFamily"
                :items="fontOptions"
                label="Font"
                variant="outlined"
                density="compact"
              />
            </v-col>
          </v-row>

          <!-- Font Size Slider -->
          <v-row dense class="mb-2">
            <v-col cols="12">
              <v-slider
                v-model="fontSize"
                label="Font Size"
                min="10"
                max="40"
                step="0.5"
                thumb-label
                density="compact"
                class="font-size-slider"
              >
                <template v-slot:append>
                  <v-chip size="small" color="lime">
                    {{ fontSize }}px
                  </v-chip>
                </template>
              </v-slider>
            </v-col>
          </v-row>

          <!-- Render As -->
          <v-radio-group v-model="renderMode" inline density="compact" class="mb-2" hide-details>
            <template #label>
              <span class="text-caption">Render as:</span>
            </template>
            <v-radio label="Transparent PNG" value="png" density="compact"></v-radio>
            <v-radio label="Composited with video (30s)" value="video" density="compact"></v-radio>
          </v-radio-group>

          <!-- Error Display -->
          <v-alert
            v-if="error"
            type="error"
            variant="tonal"
            class="mb-3"
          >
            {{ error }}
          </v-alert>
        </v-form>
      </v-card-text>

      <v-card-actions class="px-6 pb-4 d-flex">
        <v-btn color="secondary" @click="cancel" variant="outlined">
          Cancel All
        </v-btn>
        <v-spacer></v-spacer>
        <v-btn
          v-if="splitRecommendations && splitRecommendations.length > 1"
          color="success"
          @click="acceptAIRecommendation"
          :disabled="!formValid"
          :loading="loading"
          variant="elevated"
          prepend-icon="mdi-check-circle"
          class="mr-2"
        >
          Accept AI and Insert
        </v-btn>
        <v-btn
          color="deep-purple-darken-2"
          @click="rejectAIRecommendation"
          :disabled="!formValid"
          :loading="loading"
          variant="elevated"
          prepend-icon="mdi-format-quote-close"
        >
          {{ splitRecommendations && splitRecommendations.length > 1 ? 'Reject AI and Insert Original' : 'Insert Quote' }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.fsq-modal-card {
  max-height: 90vh;
  overflow-y: auto;
}

.compact-fsq-modal {
  font-size: 0.9rem;
}

.compact-fsq-modal :deep(.v-label),
.compact-fsq-modal :deep(.v-field-label),
.compact-fsq-modal :deep(.v-input__details),
.compact-fsq-modal :deep(.v-messages) {
  font-size: 0.85rem;
}

:deep(.v-field-label--floating) {
  transform: translateY(-1em) !important;
}

:deep(.v-text-field .v-field-label--floating) {
  transform: translateY(-1.7em) !important;
}

/* Larger Quote Field */
.large-quote-field :deep(textarea) {
  font-size: 16px !important;
  line-height: 1.6 !important;
  padding: 12px !important;
}

.large-quote-field :deep(.v-field__input) {
  min-height: 200px !important;
}

/* AI Processing Visual Feedback */
.ai-analyzing {
  margin-top: 7px !important;
  margin-bottom: 7px !important;
}

.ai-analyzing :deep(.v-field) {
  border: 7px solid #9C27B0 !important;
  border-radius: 0 !important;
}

.ai-analyzing :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

.ai-rejected {
  margin-top: 7px !important;
  margin-bottom: 7px !important;
}

.ai-rejected :deep(.v-field) {
  border: 7px solid #F44336 !important;
  border-radius: 0 !important;
}

.ai-rejected :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

.ai-approved {
  margin-top: 7px !important;
  margin-bottom: 7px !important;
}

.ai-approved :deep(.v-field) {
  border: 7px solid #4CAF50 !important;
  border-radius: 0 !important;
}

.ai-approved :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

.ai-auto {
  margin-top: 7px !important;
  margin-bottom: 7px !important;
}

.ai-auto :deep(.v-field) {
  border: 7px solid #2196F3 !important;
  border-radius: 0 !important;
}

.ai-auto :deep(textarea) {
  max-height: none !important;
  overflow-y: hidden !important;
}

/* AI Model Badge */
.ai-model-badge {
  position: absolute;
  bottom: 8px;
  right: 8px;
  z-index: 100;
  pointer-events: none;
  font-family: 'Courier New', monospace;
  font-size: 9px;
  line-height: 1.2;
  padding: 4px 6px;
  background: rgba(0, 0, 0, 0.85);
  color: white;
  border-radius: 2px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}

.ai-model-badge.badge-analyzing {
  border-left: 3px solid #9C27B0;
}

.ai-model-badge.badge-rejected {
  border-left: 3px solid #F44336;
}

.ai-model-badge.badge-approved {
  border-left: 3px solid #4CAF50;
}

.ai-model-badge.badge-auto {
  border-left: 3px solid #2196F3;
}

.badge-content {
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.badge-service {
  font-weight: bold;
  text-transform: uppercase;
  opacity: 0.8;
  font-size: 8px;
}

.badge-model {
  font-weight: normal;
  color: #00ff00;
}

.rotating {
  animation: rotate 2s linear infinite;
}

@keyframes rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.quote-preview-container {
  position: relative;
  width: 100%;
  min-height: 400px;
  border-radius: 0 !important;
  overflow: hidden;
  background: #000;
}

.preview-video-background {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  z-index: 1;
}

.black-bar-overlay {
  position: absolute;
  top: 10%;
  left: 0;
  width: 100%;
  height: 80%;
  background: rgba(0, 0, 0, 0.6);
  z-index: 2;
}

.quote-preview {
  position: absolute;
  top: 10%;
  left: 0;
  width: 100%;
  height: 80%;
  color: white;
  padding: 10%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  z-index: 3;
  box-sizing: border-box;
}

.quote-text {
  font-size: 1.4rem;
  font-style: italic;
  line-height: 1.4;
  font-family: Georgia, serif;
  flex-grow: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

.quote-source {
  font-size: 1rem;
  font-weight: 500;
  color: #e0e0e0;
  position: absolute;
  bottom: 5px;
  left: 10%;
  right: 10%;
  text-align: inherit;
}

.quote-timestamp {
  font-size: 0.85rem;
  color: #b0b0b0;
  font-family: 'Courier New', monospace;
}

@media (max-width: 600px) {
  .quote-text {
    font-size: 1.2rem;
  }

  .quote-source {
    font-size: 0.9rem;
  }

  .quote-timestamp {
    font-size: 0.8rem;
  }
}

.font-size-slider {
  margin-top: 8px;
}

.word-count-display {
  font-size: 12px;
  color: #666;
  text-align: left;
  margin-top: 4px;
}

.ai-feedback-message {
  font-size: 13px;
  padding: 4px 8px;
  margin-top: 4px;
  font-weight: 500;
}

.ai-message-analyzing {
  color: #9C27B0;
}

.ai-message-rejected {
  color: #D32F2F;
}

.ai-message-approved {
  color: #388E3C;
}

.ai-message-auto {
  color: #1976D2;
}

.ai-credit-text {
  font-size: 9px;
  color: #999;
  font-family: 'Courier New', monospace;
  margin-top: -8px;
  margin-bottom: 8px;
  padding-left: 4px;
  opacity: 0.7;
}

.split-segment {
  background: rgba(33, 150, 243, 0.05);
  padding: 8px 12px;
  border-radius: 0 !important;
  border-left: 3px solid #2196F3;
}

.segment-text {
  font-style: italic;
  color: #424242;
  line-height: 1.5;
}

.ai-recommendation-panel {
  border-radius: 0 !important;
}

.ai-recommendation-panel.ai-panel-analyzing {
  border: 3px solid #9C27B0;
}

.ai-recommendation-panel.ai-panel-analyzing .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(156, 39, 176, 0.1) 0%, rgba(156, 39, 176, 0.05) 100%);
}

.ai-recommendation-panel.ai-panel-rejected {
  border: 3px solid #F44336;
}

.ai-recommendation-panel.ai-panel-rejected .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(244, 67, 54, 0.1) 0%, rgba(244, 67, 54, 0.05) 100%);
}

.ai-recommendation-panel.ai-panel-approved {
  border: 3px solid #4CAF50;
}

.ai-recommendation-panel.ai-panel-approved .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(76, 175, 80, 0.1) 0%, rgba(76, 175, 80, 0.05) 100%);
}

.ai-recommendation-panel.ai-panel-auto {
  border: 3px solid #2196F3;
}

.ai-recommendation-panel.ai-panel-auto .ai-recommendation-header {
  background: linear-gradient(135deg, rgba(33, 150, 243, 0.1) 0%, rgba(33, 150, 243, 0.05) 100%);
}

.ai-recommendation-header {
  font-weight: 600;
}

.ai-recommendation-content {
  padding: 12px 0;
}

.fsq-modal-card :deep(.v-field),
.fsq-modal-card :deep(.v-text-field),
.fsq-modal-card :deep(.v-textarea),
.fsq-modal-card :deep(.v-card),
.fsq-modal-card :deep(.v-alert),
.fsq-modal-card :deep(.v-btn),
.fsq-modal-card :deep(.v-expansion-panel),
.fsq-modal-card :deep(.v-chip) {
  border-radius: 0 !important;
}
</style>

<script>
import axios from 'axios'
import { useLLM } from '@/composables/useLLM'
import aiFieldMixin from '@/mixins/aiFieldMixin'

export default {
  name: 'FsqModal',
  mixins: [aiFieldMixin],
  props: {
    show: { type: Boolean, required: true },
    currentEpisode: { type: String, default: '' },
    speakerWpm: { type: Number, default: 150 }  // Speaker WPM from profile
  },
  emits: ['update:show', 'submit'],
  data() {
    return {
      formValid: false,
      loading: false,
      error: '',
      quote: '',
      slug: '',
      source: '',
      includeAttribution: true,
      quoteStyle: 'left',
      fontFamily: 'sans-serif',
      fontSize: 25,
      renderMode: 'png',
      duration: '00:00:05:00',
      lastSubmittedSource: '',
      sourceAutopopulated: false,
      aiAnalyzing: false,
      analyzeTimeout: null,
      aiState: null,
      aiMessage: '',
      aiActionPending: false,
      aiPreviousQuote: '',
      splitRecommendations: null,
      aiGenerationInfo: null,
      aiRecommendationExpanded: [],
      analysisAbortController: null  // For cancelling in-flight analysis
    }
  },
  setup() {
    const { intelligentQuoteSplit, normalizeNestedQuotes } = useLLM()
    return { intelligentQuoteSplit, normalizeNestedQuotes }
  },
  watch: {
    show(newVal) {
      if (newVal) {
        if (this.lastSubmittedSource && !this.source) {
          this.source = this.lastSubmittedSource
          this.sourceAutopopulated = true
        }

        this.$nextTick(() => {
          if (this.$refs.quoteFieldRef) {
            this.$refs.quoteFieldRef.focus()
          }
        })
      }
    },
    source(newVal) {
      if (this.sourceAutopopulated && newVal !== this.lastSubmittedSource) {
        this.sourceAutopopulated = false
      }
    }
  },
  computed: {
    quoteRules() {
      return [
        v => !!v || 'Quote text is required',
        v => !v || v.length >= 10 || 'Quote must be at least 10 characters'
      ]
    },
    slugRules() {
      return [
        v => !!v || 'Slug is required'
      ]
    },
    sourceRules() {
      return [
        v => !!v || 'Source/attribution is required',
        v => !v || v.length <= 100 || 'Source must be 100 characters or less'
      ]
    },
    styleOptions() {
      return [
        { title: 'Centered', value: 'centered' },
        { title: 'Left Aligned', value: 'left' },
        { title: 'Right Aligned', value: 'right' },
        { title: 'Large Text', value: 'large' },
        { title: 'Elegant', value: 'elegant' }
      ]
    },
    durationOptions() {
      return [
        { title: '3 seconds', value: '00:00:03:00' },
        { title: '5 seconds', value: '00:00:05:00' },
        { title: '7 seconds', value: '00:00:07:00' },
        { title: '10 seconds', value: '00:00:10:00' },
        { title: '15 seconds', value: '00:00:15:00' },
        { title: 'Custom', value: 'custom' }
      ]
    },
    fontOptions() {
      return [
        { title: 'Sans Serif (Helvetica)', value: 'sans-serif' },
        { title: 'Serif (Georgia)', value: 'serif' },
        { title: 'Monospace (Courier)', value: 'monospace' }
      ]
    },
    previewStyle() {
      return {
        textAlign: this.quoteStyle === 'centered' ? 'center' :
                  this.quoteStyle === 'left' ? 'left' :
                  this.quoteStyle === 'right' ? 'right' : 'center'
      }
    },
    quoteTextStyle() {
      const fontMap = {
        'sans-serif': 'Helvetica, Arial, sans-serif',
        'serif': 'Georgia, "Times New Roman", serif',
        'monospace': '"Courier New", Courier, monospace'
      }
      return {
        fontFamily: fontMap[this.fontFamily] || fontMap['sans-serif'],
        fontSize: `${this.fontSize}px`
      }
    },
    quoteSourceStyle() {
      const fontMap = {
        'sans-serif': 'Helvetica, Arial, sans-serif',
        'serif': 'Georgia, "Times New Roman", serif',
        'monospace': '"Courier New", Courier, monospace'
      }
      return {
        fontFamily: fontMap[this.fontFamily] || fontMap['sans-serif']
      }
    },
    formattedQuotePreview() {
      const rawText = this.quote || 'Quote text will appear here...';
      const decoded = this.decodeQuoteText(rawText);
      const escaped = decoded
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/\n/g, '<br>');
      return '"' + escaped + '"';
    }
  },
  mounted() {
    document.addEventListener('keydown', this.handleKeydown)
  },
  beforeUnmount() {
    document.removeEventListener('keydown', this.handleKeydown)
  },
  methods: {
    // Normalize slug to lowercase with hyphens (auto-correct on blur)
    normalizeSlug() {
      if (!this.slug) return

      this.slug = this.slug
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9\s-]/g, '')  // Remove special characters
        .replace(/\s+/g, '-')           // Replace spaces with hyphens
        .replace(/-+/g, '-')            // Replace multiple hyphens with single
        .replace(/^-+|-+$/g, '')        // Remove leading/trailing hyphens
        .substring(0, 50)               // Limit to 50 characters
    },

    // Calculate duration based on word count and speaker WPM
    calculateDurationFromWPM(wordCount) {
      const wpm = this.speakerWpm || 150
      const durationInSeconds = Math.ceil((wordCount / wpm) * 60)

      const hours = Math.floor(durationInSeconds / 3600)
      const minutes = Math.floor((durationInSeconds % 3600) / 60)
      const seconds = durationInSeconds % 60

      // Return in HH:MM:SS:FF format (frames = 00 for FSQ)
      return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}:00`
    },

    hasNestedQuotes(text) {
      if (!text) return false
      const decoded = this.decodeQuoteText(text)
      const doubleQuotes = (decoded.match(/"/g) || []).length
      const singleQuotes = (decoded.match(/'/g) || []).length
      const apostrophes = (decoded.match(/[a-z]'|'[a-z]/gi) || []).length
      const actualSingleQuotes = singleQuotes - apostrophes
      const hasMixedQuotes = doubleQuotes > 0 && actualSingleQuotes > 0
      const hasMultipleDoubles = doubleQuotes > 2
      const hasMultipleSingles = actualSingleQuotes > 2
      const hasNesting = hasMixedQuotes || hasMultipleDoubles || hasMultipleSingles

      if (hasNesting) {
        console.log('🔍 Nested quotes detected:', {
          text: decoded,
          doubleQuotes,
          singleQuotes,
          apostrophes,
          actualSingleQuotes,
          hasMixedQuotes,
          hasMultipleDoubles,
          hasMultipleSingles
        })
      }

      return hasNesting
    },

    decodeQuoteText(text) {
      if (!text) return text

      let decoded = text
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/\\"/g, '"')
        .replace(/\\'/g, "'")
        .replace(/\\n/g, '\n')
        .replace(/\\r/g, '\r')
        .replace(/\\t/g, '\t')
        .replace(/\\\\/g, '\\')

      return decoded
    },

    handleKeydown(event) {
      if (event.key === 'Escape' && this.show) {
        this.cancel()
      }
    },

    async handleQuotePaste() {
      console.log('📋 Paste detected, waiting for v-model update...')
      await this.$nextTick()
      await new Promise(resolve => setTimeout(resolve, 50))
      console.log('📋 Quote pasted (length: ' + this.quote.length + ')')

      // Cancel any ongoing analysis
      this.cancelAnalysis()

      // If there's a pending action, clear it (user is pasting new content)
      if (this.aiActionPending) {
        console.log('🔄 Clearing pending AI action - user pasted new content')
        this.aiActionPending = false
        this.aiPreviousQuote = ''
      }

      // Reset AI state
      this.aiState = null
      this.aiMessage = ''
      this.splitRecommendations = null
      this.aiGenerationInfo = null

      // Use debounce for paste too (gives user time to edit after paste)
      clearTimeout(this.analyzeTimeout)
      this.analyzeTimeout = setTimeout(() => {
        if (this.quote && this.quote.length > 20) {
          console.log('🤖 Starting AI analysis after paste (2s delay)...')
          this.analyzeQuote()
        }
      }, 2000)
    },

    handleQuoteInput() {
      // Cancel any ongoing analysis immediately when user starts typing
      if (this.aiState === 'analyzing') {
        console.log('⏸️ User started typing - cancelling ongoing analysis')
        this.cancelAnalysis()
      }

      // Detect significant text changes (clearing field or major edits)
      const significantChange = Math.abs(this.quote.length - (this.aiPreviousQuote?.length || 0)) > 50

      // If there's a pending action but the text has changed significantly, reset everything
      if (this.aiActionPending && significantChange) {
        console.log('🔄 Significant text change detected - resetting AI state')
        this.aiActionPending = false
        this.aiPreviousQuote = ''
        this.aiState = null
        this.aiMessage = ''
        this.splitRecommendations = null
        this.aiGenerationInfo = null
      }

      // Clear AI state when user is actively editing (but not if there's a pending action)
      if (this.aiState && this.aiState !== 'analyzing' && !this.aiActionPending) {
        this.aiState = null
        this.aiMessage = ''
        this.splitRecommendations = null
        this.aiGenerationInfo = null
      }

      // Don't trigger new analysis if there's a pending action (user hasn't accepted/rejected yet)
      if (this.aiActionPending) {
        return
      }

      // Reset debounce timer - analysis will start 2 seconds after user stops typing
      clearTimeout(this.analyzeTimeout)
      this.analyzeTimeout = setTimeout(() => {
        if (this.quote.length > 20) {
          console.log('🤖 Triggering AI quote analysis after typing pause (2s)...')
          this.analyzeQuote()
        }
      }, 2000)
    },

    cancelAnalysis() {
      // Cancel the debounce timeout
      clearTimeout(this.analyzeTimeout)

      // Abort any in-flight API request
      if (this.analysisAbortController) {
        console.log('🛑 Aborting in-flight API request')
        this.analysisAbortController.abort()
        this.analysisAbortController = null
      }

      // Reset analyzing state
      if (this.aiState === 'analyzing') {
        this.aiAnalyzing = false
        this.aiState = null
        this.aiMessage = ''
      }
    },

    async analyzeQuote() {
      if (!this.quote || this.quote.length < 20) {
        console.log('⏭️ Quote too short for AI analysis (< 20 chars)')
        return
      }

      console.log('🤖 Starting AI quote analysis...')
      this.aiAnalyzing = true
      this.aiState = 'analyzing'
      this.aiMessage = 'AI is analyzing your quote...'

      // Create abort controller for this analysis
      this.analysisAbortController = new AbortController()

      try {
        // STEP 1: Decode escape sequences
        let workingQuote = this.decodeQuoteText(this.quote)
        if (workingQuote !== this.quote) {
          console.log('🔓 Decoded escape sequences:', { before: this.quote, after: workingQuote })
          this.aiPreviousQuote = this.quote
          this.quote = workingQuote
          this.aiState = 'auto'
          this.aiMessage = 'AI decoded escape sequences in your quote text'
          this.aiActionPending = true
          return
        }

        // STEP 2: Check for nested quotes
        if (this.hasNestedQuotes(workingQuote)) {
          console.log('📝 Nested quotes detected, normalizing...')
          this.aiMessage = 'Nested quotes detected - normalizing quotation marks...'
          const normalized = await this.normalizeNestedQuotes(workingQuote)

          if (normalized !== this.quote) {
            console.log('✨ Quote normalized:', { before: this.quote, after: normalized })
            this.aiPreviousQuote = this.quote
            this.quote = normalized
            workingQuote = normalized
            // Don't return - continue to split analysis with normalized quote
            console.log('⏭️ Continuing to split analysis with normalized quote...')
          }
        }

        // STEP 3: Load settings
        this.aiState = 'analyzing'
        this.aiMessage = 'AI is checking if quote needs to be split...'

        console.log('📥 Loading generation settings from backend...')
        const settingsResponse = await axios.get('/api/settings/', {
          headers: {
            'X-API-Key': 'FDT5WyO7S2DbBifbDUEsd1H8cmZTT3_qpJXtb3c7qaY'
          }
        })

        const settings = settingsResponse.data.generation || {}
        console.log('⚙️ Generation settings loaded:', settings)

        const splitConfig = {
          maxLines: settings.fsq_max_lines || 5,
          charsPerLine: settings.fsq_chars_per_line || 50,
          fontSize: settings.default_font_size || '19px',
          minSecondScreen: settings.fsq_min_second_screen || 80,
          splitStrategy: settings.fsq_split_strategy || 'smart',
          balanceThresholdPercent: settings.fsq_balance_threshold_percent || 30,
          preferSentenceBoundaries: settings.fsq_prefer_sentence_boundaries !== false,
          allowMidSentenceSplit: settings.fsq_allow_mid_sentence_split || false,
          overflowHandling: settings.fsq_overflow_handling || 'multi_segment'
        }

        console.log('🧮 Smart Split Config:', splitConfig)

        // STEP 4: Call AI for split analysis
        console.log('🧠 Calling intelligentQuoteSplit() with smart split logic...')
        const segments = await this.intelligentQuoteSplit(workingQuote, splitConfig)

        console.log('✅ AI quote analysis result:', segments)

        const now = new Date()
        this.aiGenerationInfo = {
          model: 'qwen2.5-coder:7b',
          timestamp: now.toLocaleString('en-US', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
          })
        }

        if (segments.length > 1) {
          this.aiState = 'rejected'
          this.aiMessage = `AI recommends splitting this quote into ${segments.length} separate FSQ cues`
          this.splitRecommendations = segments
          this.aiRecommendationExpanded = []

          console.log(`✂️ AI recommends splitting into ${segments.length} segments`)
          console.log('📋 Recommendation panel ready - invitation banner will prompt user to expand')
          console.log('💬 AI Message set to:', this.aiMessage)
        } else {
          this.aiState = 'approved'
          this.aiMessage = 'AI approved - quote fits perfectly as a single full-screen graphic'
          this.splitRecommendations = null
          this.aiRecommendationExpanded = []

          console.log('✅ AI approved - quote fits as single FSQ')
          console.log('💬 AI Message set to:', this.aiMessage)
          console.log('🎨 AI State set to:', this.aiState)
        }
      } catch (error) {
        // Silently ignore aborted requests (user cancelled by typing)
        if (error.name === 'AbortError' || error.message?.includes('abort')) {
          console.log('⏸️ Analysis aborted by user')
          return
        }

        console.error('Quote analysis failed:', error)
        this.aiState = null
        this.aiMessage = `Analysis failed: ${error.message || 'Unknown error'}`
      } finally {
        this.aiAnalyzing = false
        this.analysisAbortController = null
      }
    },

    generateSlugFromQuote(quoteText) {
      return quoteText
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-+|-+$/g, '')
        .substring(0, 50)
        || 'fsq-quote'
    },

    splitQuoteIntoSegments(quoteText, maxLength = 300) {
      if (quoteText.length <= maxLength) {
        return [quoteText]
      }

      const segments = []
      let currentSegment = ''

      const sentences = quoteText.match(/[^.!?]+[.!?]+|[^.!?]+$/g) || [quoteText]

      for (const sentence of sentences) {
        if ((currentSegment + sentence).length <= maxLength) {
          currentSegment += sentence
        } else {
          if (currentSegment) {
            segments.push(currentSegment.trim())
          }
          currentSegment = sentence
        }
      }

      if (currentSegment) {
        segments.push(currentSegment.trim())
      }

      return segments
    },

    async submit() {
      const isValid = await this.$refs.fsqFormRef.validate()
      console.log('Form validation result:', isValid)
      if (!isValid) {
        console.warn('Form validation failed')
        return
      }

      // Cancel any ongoing AI analysis - user has made their decision
      if (this.aiAnalyzing) {
        console.log('⏸️ User submitted during analysis - cancelling AI analysis')
        this.cancelAnalysis()
      }

      this.loading = true
      this.error = ''

      try {
        const currentEpisode = this.$route.params.episode || this.currentEpisode

        if (!currentEpisode) {
          throw new Error('No episode ID available')
        }

        const quoteSegments = this.splitRecommendations && this.splitRecommendations.length > 0
          ? this.splitRecommendations
          : [this.quote.trim()]

        console.log(`Creating ${quoteSegments.length} FSQ cue(s)`)

        if (this.includeAttribution && this.source.trim()) {
          this.lastSubmittedSource = this.source.trim()
        }

        for (let i = 0; i < quoteSegments.length; i++) {
          const segment = quoteSegments[i]
          const isMultipart = quoteSegments.length > 1

          const assetId = await this.generateAssetId()
          // Use user-entered slug, add part suffix for multipart quotes
          const slug = isMultipart ? `${this.slug}-part-${i + 1}` : this.slug

          console.log(`Creating FSQ cue ${i + 1}/${quoteSegments.length} (media generation deferred)...`)

          const wordCount = segment.trim().split(/\s+/).filter(word => word.length > 0).length;
          const cleanQuote = this.decodeQuoteText(segment);

          // Calculate duration based on word count and speaker WPM
          const calculatedDuration = this.calculateDurationFromWPM(wordCount);

          const cueData = {
            type: 'FSQ',
            assetId: assetId,
            slug: slug,
            quote: cleanQuote,
            style: this.quoteStyle,
            fontFamily: this.fontFamily,
            fontSize: this.fontSize,
            renderMode: this.renderMode,
            duration: calculatedDuration,
            wordCount: wordCount,
            part: isMultipart ? `${i + 1}x${quoteSegments.length}` : '1x1'
          }

          if (this.includeAttribution && this.source.trim()) {
            cueData.source = this.source.trim()
          }

          console.log(`Creating FSQ cue ${i + 1} with asset:`, cueData)

          this.$emit('submit', cueData)

          // No delay between segments - user can place them consecutively
        }

        this.reset()
        this.$emit('update:show', false)

      } catch (error) {
        console.error('Error creating FSQ cue:', error)
        this.error = error.response?.data?.detail || 'Failed to create quote cue. Please try again.'
      } finally {
        this.loading = false
      }
    },

    cancel() {
      this.$emit('update:show', false)
      this.reset()
    },

    async generateAssetId() {
      try {
        console.log('Requesting AssetID for FSQ cue')

        const slug = this.quote.trim()
          .toLowerCase()
          .replace(/[^a-z0-9\s-]/g, '')
          .replace(/\s+/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-+|-+$/g, '')
          .substring(0, 50)

        const formData = new FormData()
        formData.append('slug', slug || 'fsq-quote')
        formData.append('type', 'fsq')

        const response = await axios.post('/assetid/generate-legacy', formData, {
          headers: {
            'Accept': 'application/json',
            'X-API-Key': 'FDT5WyO7S2DbBifbDUEsd1H8cmZTT3_qpJXtb3c7qaY'
          }
        })

        if (response.data && response.data.id) {
          console.log('Successfully generated AssetID:', response.data.id)
          return response.data.id
        } else {
          throw new Error('Invalid response format: missing id field')
        }
      } catch (error) {
        console.warn('AssetID generation failed, using fallback:', error)
        const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
        let result = 'LOCAL_FSQ_'
        for (let i = 0; i < 8; i++) {
          result += chars.charAt(Math.floor(Math.random() * chars.length))
        }
        console.log('Generated local fallback AssetID:', result)
        return result
      }
    },

    reset() {
      // Cancel any ongoing analysis
      this.cancelAnalysis()

      this.quote = ''
      this.slug = ''
      this.source = ''
      this.sourceAutopopulated = false
      this.includeAttribution = true
      this.quoteStyle = 'left'
      this.fontFamily = 'sans-serif'
      this.fontSize = 25
      this.duration = '00:00:05:00'
      this.error = ''
      this.loading = false
      this.aiState = null
      this.splitRecommendations = null
      this.aiGenerationInfo = null
      this.aiActionPending = false
      this.aiPreviousQuote = ''

      this.$nextTick(() => {
        if (this.$refs.fsqFormRef) {
          this.$refs.fsqFormRef.resetValidation()
        }
      })
    },

    acceptAIChange() {
      console.log('✅ User accepted AI change')
      this.aiActionPending = false
      this.aiPreviousQuote = ''
      this.aiMessage = ''
      this.analyzeQuote()
    },

    rejectAIChange() {
      console.log('❌ User rejected AI change - reverting')
      this.quote = this.aiPreviousQuote
      this.aiPreviousQuote = ''
      this.aiActionPending = false
      this.aiState = null
      this.aiMessage = ''
    },

    async acceptAIRecommendation() {
      console.log('Accepting AI split recommendation and submitting...')
      await this.submit()
    },

    async rejectAIRecommendation() {
      this.splitRecommendations = null
      this.aiState = null
      this.aiGenerationInfo = null
      await this.submit()
    },

    async suggestDifferentSplit() {
      console.log('Requesting alternative split suggestion...')

      if (!this.quote || this.quote.length < 20) {
        console.warn('Quote too short for alternative split analysis')
        return
      }

      this.aiAnalyzing = true
      this.aiState = 'analyzing'

      try {
        const settingsResponse = await axios.get('/api/settings/', {
          headers: {
            'X-API-Key': 'FDT5WyO7S2DbBifbDUEsd1H8cmZTT3_qpJXtb3c7qaY'
          }
        })

        const settings = settingsResponse.data.generation || {}

        const splitConfig = {
          maxLines: settings.fsq_max_lines || 5,
          charsPerLine: settings.fsq_chars_per_line || 50,
          fontSize: settings.default_font_size || '19px',
          minSecondScreen: settings.fsq_min_second_screen || 80,
          splitStrategy: settings.fsq_split_strategy || 'smart',
          balanceThresholdPercent: settings.fsq_balance_threshold_percent || 30,
          preferSentenceBoundaries: settings.fsq_prefer_sentence_boundaries !== false,
          allowMidSentenceSplit: settings.fsq_allow_mid_sentence_split || false,
          overflowHandling: settings.fsq_overflow_handling || 'multi_segment',
          temperature: 0.5
        }

        const segments = await this.intelligentQuoteSplit(this.quote, splitConfig)

        console.log('Alternative AI quote analysis result:', segments)

        const now = new Date()
        this.aiGenerationInfo = {
          model: 'qwen2.5-coder:7b',
          timestamp: now.toLocaleString('en-US', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
          })
        }

        if (segments.length > 1) {
          this.aiState = 'rejected'
          this.splitRecommendations = segments
          console.log('New split suggestion:', segments.length, 'segments')
        } else {
          this.aiState = 'approved'
          this.splitRecommendations = null
          setTimeout(() => {
            this.aiState = null
          }, 2000)
        }
      } catch (error) {
        console.error('Alternative split analysis failed:', error)
        this.aiState = 'rejected'
      } finally {
        this.aiAnalyzing = false
      }
    }
  }
}
</script>
