"""GET /episodes/{slug}/thumbnails — resolved poster set with srcset.

Returns PublicPosterVariants per ratio. URLs point at media.disaffected.com.
Resizing pre-generated by public.generate_poster_variants Celery task
(queue: assets).
"""
from fastapi import APIRouter, Depends, HTTPException

from ._shared import require_public_read

router = APIRouter()


@router.get('/episodes/{slug}/thumbnails')
async def get_episode_thumbnails(
    slug: str,
    _principal=Depends(require_public_read),
):
    """STUB — returns 501 until implemented. See plan §Phase 2."""
    raise HTTPException(status_code=501, detail='not_implemented_phase_2')
